export const TRANSLATIONS = {
  "ar": {
    "faTitle": "الإسعافات الأولية",
    "faHint": "إنعاش · اختناق · إصابات",
    "faCall": "اتصل بـ999",
    "faEmergency": "فيه خطر على الحياة؟ اتصل بـ999، شغّل مكبّر الصوت واتبع تعليمات الإسعاف.",
    "faCprTab": "فاقد الاستجابة / إنعاش",
    "faChokeTab": "اختناق",
    "faRecoveryTab": "بيتنفس طبيعي",
    "faInjuriesTab": "نزيف / إصابات",
    "faAdult": "الخطوات دي للبالغين. لو طفل أو رضيع، اتصل بـ999 واتبع التعليمات المناسبة لعمره.",
    "faCprTitle": "مش بيستجيب وتنفسه مش طبيعي",
    "faCheckTitle": "افحص الخطر والاستجابة",
    "faCheck": "اتأكد إن الاقتراب آمن. كلّمه والمس كتفيه برفق لفحص الاستجابة، ونادِ على حد يساعدك.",
    "fa999Title": "مفيش استجابة؟ اتصل بـ999 فورًا",
    "fa999": "شغّل مكبّر الصوت. افتح مجرى الهواء بإمالة الرأس ورفع الذقن، وافحص التنفس مع موظف الإسعاف. الشهقات المتقطعة مش تنفس طبيعي.",
    "faPressTitle": "مفيش تنفس طبيعي؟ ابدأ الإنعاش",
    "faPress": "حط إيديك فوق بعض في منتصف الصدر وذراعيك مفرودين. اضغط بعمق 5–6 سم، بمعدل 100–120 في الدقيقة، وسيب الصدر يرجع بالكامل بين الضغطات.",
    "faBreaths": "لو متدرّب وقادر ومستعد: 30 ضغطة ثم نفختين. غير كده استمر في ضغطات الصدر واتبع تعليمات 999.",
    "faContinue": "استمر لحد ما المختصين يستلموا أو يطلبوا التوقف، أو يرجع التنفس الطبيعي/علامات الحياة، أو تعجز عن الاستمرار. توقف مؤقتًا لما جهاز الصدمات يطلب.",
    "faAedTitle": "استخدم جهاز الصدمات أول ما يوصل",
    "faAed": "ابعت مساعد يجيب جهاز الصدمات؛ 999 يقدر يرشده لمكانه. ما تسيبش المصاب لوحده وتروح تدور. شغّل الجهاز واتبع تعليماته، وركّب اللاصقات على الجلد المكشوف حسب الرسم.",
    "faAedClear": "واصل الضغطات والمساعد بيركّب اللاصقات. محدش يلمس المصاب وقت التحليل أو الصدمة. ارجع للإنعاش فورًا حسب التعليمات، حتى لو الجهاز قال الصدمة مش مطلوبة.",
    "faChildAed": "جهاز الصدمات ينفع للأطفال. استخدم وضع/لاصقات الأطفال لو متاحة واتبع 999 وتعليمات الجهاز؛ ما تؤخرش استخدامه لمجرد إن المتاح وضع البالغين.",
    "faRecoveryTitle": "مش بيستجيب لكنه بيتنفس طبيعي",
    "faRecoveryWarning": "اتصل بـ999 وراقب التنفس باستمرار. بعد إصابة أو اشتباه إصابة رقبة/ظهر، تجنب تحريكه واتبع 999 لتأمين مجرى الهواء. الشهقات تستدعي الإنعاش، مش وضع الإفاقة.",
    "faRecovery1": "لو مفيش إصابة: حط الذراع القريبة منك بزاوية قائمة والكف لفوق. ثبّت ظهر الإيد التانية على الخد القريب منك.",
    "faRecovery2": "اثنِ الركبة البعيدة وثبّت القدم على الأرض. مع تثبيت الإيد على الخد، لفّه برفق ناحيتك على جنبه.",
    "faRecovery3": "اثنِ الرجل اللي فوق لتثبيت الوضع. أمل الرأس وارفع الذقن لفتح مجرى الهواء. خليك معاه؛ لو التنفس الطبيعي وقف ابدأ الإنعاش.",
    "faChokeTitle": "اختناق شخص بالغ",
    "faCoughTitle": "بيكح بقوة؟ شجّعه يكح",
    "faCough": "خليك معاه. لو الكحة فعّالة، ما تعملش ضربات ظهر أو ضغطات. لو مش قادر يتكلم أو يتنفس أو يكح بفاعلية، اتصرف فورًا.",
    "faBackTitle": "حتى 5 ضربات ظهر",
    "faBack": "اطلب من حد يتصل بـ999. قف خلفه وعلى جنب شوية. اسند صدره وميّله لقدّام واضرب بين لوحي الكتف بكعب إيدك. افحص بعد كل ضربة.",
    "faThrustTitle": "لسه مسدود؟ حتى 5 ضغطات بطن",
    "faThrust": "قف وراه وحاوط خصره. حط قبضة فوق السرّة وتحت الضلوع، امسكها بإيدك التانية واسحب بقوة لجوه ولفوق.",
    "faChokeNext": "لو الانسداد مستمر، اتأكد إن 999 اتطلب، وبدّل بين حتى 5 ضربات ظهر و5 ضغطات. توقف لما الانسداد يزول. لو فقد الاستجابة، ابدأ الإنعاش واتبع 999.",
    "faChokeWarning": "ما تدخلش صوابعك في الفم للبحث عن جسم مش ظاهر. ما تعملش ضغطات بطن للحامل أو الرضيع؛ اطلب من 999 الطريقة المناسبة.",
    "faChokeAfter": "بعد ضغطات البطن لازم تقييم طبي، حتى لو الانسداد زال.",
    "faBleedTitle": "نزيف شديد أو مش بيقف",
    "faBleed1": "اتصل بـ999 للنزيف الشديد. البس قفازات لو متاحة، واضغط بثبات على الجرح بقماشة نظيفة أو ضمادة.",
    "faBleed2": "ما تشيلش جسم مغروس ولا تضغط عليه؛ اضغط على جانبيه. لو الدم عدّى الضمادة، ضيف واحدة فوقها وواصل الضغط.",
    "faShock": "برودة وعرق، ضعف، تشوش أو دوخة بعد الإصابة ممكن تكون صدمة. اتصل بـ999، حافظ على دفئه وراقب تنفسه، وما تدّيلوش أكل أو شرب. تجنب تحريك الأطراف المصابة.",
    "faCutsTitle": "جروح وخدوش بسيطة",
    "faCuts": "بعد توقف النزيف: نظّف إيديك، اغسل الجرح بمياه نظيفة وغطّيه بضمادة معقمة. ما تحطش كحول أو مطهّر جواه. اطلب نصيحة 111 لو فيه أوساخ باقية أو علامات عدوى أو عضة.",
    "faBonesTitle": "اشتباه كسر أو إصابة رأس",
    "faBones": "اسند الجزء المصاب في وضعه؛ ما تحاولش تعدّله أو تحمّله وزن. رتّب تقييم طبي عاجل. لو فيه اشتباه إصابة رقبة/ظهر، خليه ثابت واتصل بـ999.",
    "faHead": "بعد ضربة الرأس، اتصل بـ999 لو مش بيفوق أو مش قادر يفضل صاحي، حصل تشنج، أو ظهرت مشكلة كلام أو اتزان أو حركة. للقيء أو الدوخة أو أي قلق تاني، اطلب نصيحة عاجلة من 111. ما تسيبوش لوحده.",
    "faSprainTitle": "التواء أو شدّ بسيط",
    "faSprain": "احمِ المكان وريّحه. كمادة تلج ملفوفة بفوطة لحد 20 دقيقة كل 2–3 ساعات؛ مش مباشرة على الجلد. اسنده وارفعه لو مريح. اطلب تقييم طبي للألم الشديد أو التشوه أو التنميل أو عدم القدرة على تحميل الوزن.",
    "faBurnLink": "حروق: افتح خطوات التبريد",
    "faReportLink": "بعد تأمين الحالة: بلّغ بالواقعة",
    "faHelpLink": "حد اتصاب؟ افتح الإسعافات",
    "faWorkTitle": "قبل شيفتك",
    "faWork": "اعرف مين المسعفين، مكان شنطة الإسعاف وجهاز الصدمات، وطريقة استدعاء المساعدة في فرعك. اسأل مديرك لو مش متأكد.",
    "faSources": "المصادر وحدود الدليل",
    "faSourceNote": "مرجع سريع للبالغين، مش شهادة تأهيل إسعافي. اتراجع مع الإرشادات البريطانية يوم 9 أكتوبر 2026. اتبع تعليمات 999 وترتيبات مكان شغلك.",
    "incidentTitle": "الإبلاغ عن حادث أو حادث وشيك",
    "incidentQuick": "حادث أو حادث وشيك؟",
    "homeHazardTitle": "خطر أو وضع غير آمن؟",
    "homeHazardHint": "راجع الخطر وبلّغ المسؤول",
    "incidentQuickHint": "إصابة أو حادث وشيك · اتبع خطوات الإبلاغ",
    "incidentIntro": "حتى لو محدش اتصاب، الواقعة اللي كان ممكن تسبب ضرر لازم تتراجع ويتبلّغ عنها.",
    "incidentClassifyTitle": "حدّد نوع الواقعة",
    "incidentNearTitle": "حادث وشيك — Near Miss",
    "incidentNearDesc": "حصل موقف كان ممكن يسبب إصابة أو ضرر، لكن الضرر ما حصلش.",
    "incidentAccidentTitle": "حادث فعلي — Accident",
    "incidentAccidentDesc": "حصلت إصابة أو تلف بالفعل. اطلب المساعدة المناسبة وبلّغ بالواقعة.",
    "incidentStepsTitle": "خمس خطوات للتعامل والإبلاغ",
    "incidentStep1Title": "أمّن المكان",
    "incidentStep1Desc": "افحص الخطر الفوري وأزله فقط لو تقدر بأمان. لو مش آمن، ابعد الناس وبلّغ.",
    "incidentStep2Title": "اطمئن على الناس",
    "incidentStep2Desc": "اتأكد إن المشاركين بخير واطلب إسعافًا أوليًا أو طوارئ لو فيه حاجة.",
    "incidentStep3Title": "بلّغ المدير",
    "incidentStep3Desc": "اشرح الواقعة وسجّل: إمتى، فين، مين شارك أو شاف، وإيه اللي حصل.",
    "incidentStep4Title": "سجّل البلاغ",
    "incidentStep4Desc": "استخدم نظام الشركة المعتمد، وحدّد نوع الواقعة والفرع الصحيح بدقة.",
    "incidentStep5Title": "امنع تكرارها",
    "incidentStep5Desc": "راجع السبب مع المدير وتابع الإجراءات اللي تمنع وقوع نفس الخطر تاني.",
    "incidentRecordTitle": "البيانات اللي تحتاجها للبلاغ",
    "incidentRecordWhen": "إمتى؟ التاريخ والوقت",
    "incidentRecordWhere": "فين؟ مكان الواقعة",
    "incidentRecordWho": "مين؟ الأشخاص والشهود",
    "incidentRecordWhat": "إيه؟ الشغل اللي كان بيحصل وتفاصيل الواقعة",
    "incidentAlertTitle": "التسجيل على Alert65",
    "incidentAlertIntro": "فيديو تدريب الشركة بيعرض المسار ده:",
    "incidentAlertSelect": "اختار المجموعة والفرع الصحيحين، وبعدها نوع الواقعة. فيه اختيار Near miss مستقل عن Accident.",
    "incidentAlertSave": "كمّل الحقول المطلوبة حسب النوع، وتأكد إن البلاغ اتبعت فعلًا؛ الحفظ وحده مش تأكيد للإرسال.",
    "incidentAlertNote": "صور التدريب بتعرض مثال Accident على فرع Cairn Lodge؛ مش معناها تختار الفرع ده أو تسجّل الحادث الوشيك كـ Accident.",
    "incidentEscalate": "لو فيه خطر فوري أو إصابة خطيرة، سلامة الناس وطلب المساعدة العاجلة أهم من استكمال النموذج.",
    "riskQuickTitle": "تقييم الخطر قبل المهمة",
    "riskQuickIntro": "الخطر = حاجة ممكن تسبب أذى. مستوى المخاطرة بيتحدد من احتمال الأذى وشدته.",
    "riskStep1Title": "حدّد",
    "riskStep1Desc": "إيه الخطر، ومين ممكن يتأذى؟",
    "riskStep2Title": "قيّم",
    "riskStep2Desc": "احتمال الإصابة وشدتها؛ ابدأ بالأعلى خطورة.",
    "riskStep3Title": "تحكّم",
    "riskStep3Desc": "شيل مصدر الخطر إن أمكن، وقلّل التعرض قبل الاعتماد على معدات الوقاية.",
    "riskOrderTitle": "ترتيب وسائل التحكم في الخطر",
    "riskOrderIntro": "ابدأ بالأكثر فاعلية؛ معدات الوقاية آخر مستوى، مش أول حل.",
    "riskOrder1": "إزالة مصدر الخطر",
    "riskOrder2": "استبداله ببديل أكثر أمانًا",
    "riskOrder3": "عزل الخطر بوسيلة هندسية",
    "riskOrder4": "تغيير طريقة العمل والتعليمات",
    "riskOrder5": "معدات الحماية الشخصية (PPE)",
    "riskReportLink": "حادث أو موقف كان ممكن يسبب أذى؟ افتح خطوات الإبلاغ",
    "knifeGuideTitle": "استخدام السكاكين بأمان",
    "knifeGuide1": "قبل الاستخدام: اختار سكينة مناسبة للمهمة، وتأكد إنها حادة وسليمة.",
    "knifeGuide2": "أثناء نقلها: خلي طرف النصل لتحت جنب جسمك؛ ما توجهوش لقدّام أو لفوق.",
    "conflictGuideTitle": "لو حصل تهديد أو سلوك عدواني",
    "conflictGuide1": "اتكلم بهدوء ووضوح، اسمع وأظهر تفهمًا من غير تصعيد أو تحدّي.",
    "conflictGuide2": "ابعد لمكان آمن واطلب مساعدة لو فيه خطر؛ بلّغ عن أي عنف أو تهديد في العمل.",
    "loneGuideTitle": "الشغل لوحدك — قبل الشيفت",
    "loneGuide1": "اعرف مين بيتابع سلامتك ومواعيد التواصل المتفق عليها وطريقة طلب النجدة. اسأل عن المهام اللي ممنوع تعملها بمفردك.",
    "loneGuide2": "لو حاسس بخطر أو مش قادر توصل للمساعدة أو فيه تهديد، ابعد لمكان آمن واتبع خطة طوارئ فرعك. اتصل بـ999 لو الخطر فوري.",
    "dseGuideTitle": "العمل على شاشة — وضع مريح",
    "dseGuide1": "خلي الشاشة قدامك وعلى بُعد ذراع تقريبًا، وأعلاها عند مستوى العين. اسند أسفل ظهرك، ريّح كتافك وخلي ساعديك أفقيين تقريبًا.",
    "dseGuide2": "قلّل انعكاس الضوء، وسيب مساحة فاضية لرجليك، وغيّر النشاط أو خد فواصل قصيرة منتظمة. بلّغ لو فيه ألم مستمر أو تجهيز غير مناسب.",

    "ppeActionLink": "افتح خطوات فحص معدات الوقاية في سلامة الشغل",
    "poisonQuick": "ابتلاع مادة تنظيف",
    "poisonQuickHint": "تصرف فورًا عند الاشتباه بالتسمم",
    "ppeActionHeading": "قبل استخدام معدات الوقاية",
    "ppeActionCheck": "اعرف معدات الحماية المطلوبة للمهمة وطريقة استخدامها.",
    "ppeActionFault": "افحص المعدات. لو ناقصة أو تالفة، ما تبدأش المهمة وبلّغ المشرف.",
    "ppeActionWear": "استخدمها حتى في المهام القصيرة، ونظّفها وخزّنها حسب التعليمات.",
    "signGuideHeading": "اتعرّف على لافتات السلامة",
    "signGuideHint": "خلي بالك من اللون والشكل، واقرأ الرمز الموجود على اللافتة.",
    "sign_red_title": "ممنوع",
    "sign_red_detail": "زي ممنوع الدخول",
    "sign_yellow_title": "تحذير",
    "sign_yellow_detail": "انتبه وخد احتياطاتك",
    "sign_blue_title": "إلزامي",
    "sign_blue_detail": "اتبع التعليمات المطلوبة",
    "sign_green_title": "إسعافات وطوارئ",
    "sign_green_detail": "مخارج وإسعافات أولية",
    "poisonTitle": "لو حد ابتلع مادة تنظيف",
    "poisonAction": "اطلب مساعدة طبية فورًا: اتصل بـ999 أو توجّه للطوارئ. ما تحاولش تخليه يرجّع، وما تديلوش أكل أو شرب. خد عبوة المادة أو نشرة السلامة لو متاحة، من غير ما تأخر المساعدة.",
    "poisonNHS": "إرشادات الخدمة الصحية عن التسمم",
    "fireGuideLabel": "دليل سريع للتصرف",
    "firePriorityLabel": "الأولوية دائمًا",
    "fireDiscoveredTitle": "لو اكتشفت حريق",
    "fireEvacTitle": "لو سمعت إنذار الحريق",
    "fireChecklistHint": "القائمة للمراجعة والتدريب فقط. وقت الحريق اخرج فورًا من غير ما تشغل نفسك بالمربعات.",
    "fireEvacuateNotice": "لو الإنذار اشتغل، ابدأ الإخلاء فورًا. ما تتأخرش علشان تقرأ الصفحة.",
    "firePracticeTitle": "قائمة مراجعة الإخلاء",
    "firePracticeHint": "للتدريب أو المراجعة فقط — مش أثناء الحريق",
    "fireEquipmentToggleHint": "٥ أنواع · افتح المرجع",
    "fireCall999": "من مكان آمن: اتصل بـ999 لو البلاغ لسه ما اتعملش",
    "fireGuidanceTitle": "أثناء الخروج وبعده",
    "fireNoReturnTitle": "ما ترجعش للمبنى",
    "fireUnsafeTitle": "لو النار أو الدخان زادوا",
    "fireReportTitle": "بلّغ من مكان آمن",
    "fireRolesTitle": "مهام إضافية حسب مسؤوليتك",
    "fireRolesIntro": "الإخلاء أهم من إكمال أي مهمة. ما تدخلش مكان خطر علشان تراجع حاجة.",
    "fireForecourtHint": "راجع الأماكن المذكورة فقط لو الوضع آمن.",
    "fireWardenHint": "للموظف المكلّف بالدور ده فقط.",
    "fireReferenceTitle": "التعرّف على معدات الإطفاء",
    "fireReferenceIntro": "مرجع سريع للتعرّف على الأنواع، مش بديل لتدريب الموقع.",

    "extVisualTitle": "التعرّف على أنواع الطفايات",
    "extVisualWarning": "مرجع تعليمي فقط: الإخلاء أولًا. استخدام الطفاية فقط للمتدرّب والمصرّح له ومع وجود طريق هروب آمن. اقرأ ملصق الطفاية الفعلية.",
    "extVisualNote": "الألوان المعروضة للتعرّف على الأنواع الشائعة، وليست تأكيدًا للمعدات الموجودة في موقع العمل. راجع الملصق وخطة الحريق.",
    "chemicalVisualTitle": "راجع ملصق عبوة التنظيف الفعلية",
    "chemicalVisualNote": "لازم نتأكد من اسم المنتج وكوده ومعدات الحماية من ملصق الموقع ونشرة بيانات السلامة. منتج D10 غير مؤكّد حتى الآن.",

    "safetyQuick": "سلامة الشغل",
    "safetyQuickHint": "حروق · مخاطر · رفع أحمال · مواد خطرة",
    "burnTab": "حروق",
    "hazardTab": "مخاطر",
    "liftingTab": "رفع أحمال",
    "substanceTab": "مواد خطرة",
    "burnTitle": "حرق من حرارة أو سائل ساخن",
    "burn1": "ابدأ تبريد المكان بمياه جارية باردة باعتدال لمدة ٢٠ دقيقة.",
    "burn2": "شيل الملابس والحُلي القريبة، لكن ما تشيلش أي حاجة لازقة في الحرق.",
    "burn3": "بعد التبريد، غطّه بطبقة بلاستيك تغليف نظيفة؛ ما تلفّهاش حوالين الطرف وما تحطّهاش على الوجه.",
    "burn4": "ممنوع التلج والكريمات والزيوت والزبدة. حافظ على دفء باقي الجسم واطلب مساعدة المسعف في الموقع.",
    "burnUrgentTitle": "مساعدة طبية عاجلة",
    "burnUrgent": "اتصل بـ999 أو اطلب الوصول للطوارئ لو الحرق كبير أو عميق، أو في الوجه أو الأعضاء التناسلية أو المؤخرة، أو سببه كهرباء أو مادة كيميائية. لو مش متأكد، اطلب نصيحة NHS 111.",
    "burnScope": "الخطوات هنا للحروق الحرارية والسوائل الساخنة. التعرض الكيميائي له تعليمات منفصلة.",
    "nhsBurnGuide": "إرشادات NHS للحروق",
    "hazardTitle": "خطر أو عطل في مكان الشغل",
    "hazard1": "وقف المهمة لو مش آمنة. بلّغ المشرف فورًا بالخطر ومكانه.",
    "hazard2": "ما تستخدمش معدات معيبة أو معدات جديدة من غير تدريب وتعليمات.",
    "hazard3": "لو المشكلة اتبلغت ولسه قائمة، تابع مع المدير؛ البلاغ مش معناه إن العطل اتصلّح.",
    "wetFloorTitle": "انسكاب أو طريق غير آمن",
    "wetFloor1": "خلي الطريق واضح من العوائق والكابلات. بلّغ عن الأرضية أو الحصيرة التالفة.",
    "wetFloor2": "نظّف الانسكاب العادي فورًا لو متدرّب وآمن؛ نشّف المكان وحط علامة أرضية مبلولة أثناء البلل.",
    "wetFloor3": "وقود أو مادة كيميائية أو مادة مش معروفة؟ ابعد الناس وبلّغ المشرف؛ اتبع إجراء الموقع المخصص.",
    "liftingTitle": "قبل رفع أو نقل حمولة",
    "lifting1": "قيّم الحمولة والطريق وقدرتك. لو تقيلة أو مش قادر تمسكها، وقف واطلب مساعدة أو وسيلة نقل مناسبة.",
    "lifting2": "ثبّت رجليك، قرّب الحمولة، اثني الركب وحافظ على وضع ظهر طبيعي. ارفع بسلاسة مع فرد الرجلين.",
    "lifting3": "خلي الجانب الأتقل قريب من جسمك. لف برجليك بدل ما تلوي ظهرك، وخلي الطريق قدامك واضح.",
    "lifting4": "نزّلها بهدوء. استخدم عربة مناسبة للمسافات الطويلة؛ ادفع بدل السحب لما يكون آمن ومناسب للمعدة.",
    "substanceTitle": "قبل التعامل مع مادة خطرة",
    "substance1": "راجع الملصق وتعليمات الشغل الآمن وتقييم COSHH للمنتج. لو التعليمات أو التدريب ناقصين، اسأل المشرف قبل الاستخدام.",
    "substance2": "استخدم وسائل التحكم ومعدات الوقاية المطلوبة للمهمة. رمز الخطر لوحده مش بيحدد الحماية المطلوبة.",
    "substance3": "خلي بالك من الغبار والأبخرة والغازات، مش بس العبوات. المادة ممكن تدخل بالتنفس أو البلع أو الجلد والعين أو جرح.",
    "substance4": "تسرّب أو تعرض؟ وقف المهمة، ابعد عن الخطر وبلّغ المشرف. اتبع تعليمات الطوارئ الخاصة بالمادة.",
    "fireRaise": "اكتشفت حريق؟ نادي «حريق!» وفعّل أقرب إنذار لو آمن، وبعدها اخرج.",
    "fireLeave": "ما تجريش، ما تستخدمش المصعد، وما ترجعش لمتعلقاتك أو للمبنى قبل السماح.",
    "fireStop": "النار بتنتشر أو حسيت بحرارتها؟ وقف محاولة الإطفاء واخرج فورًا. لو فيه دخان أثناء الخروج، خليك منخفض.",
    "firePassTitle": "الطفاية — لو متدرّب ومسموح لك فقط",
    "firePassGuard": "فقط لحريق صغير، مع طفاية مناسبة وطريق هروب آمن. لو مش مرتاح، اخرج.",
    "firePass": "خطوات استخدام الطفاية: اسحب مسمار الأمان · وجّه لقاعدة النار من مسافة آمنة · اضغط المقبض · حرّك الفوهة يمين وشمال.",
    "fireContact": "بلّغ مسؤول الحريق بمكان النار وأي شخص مفقود أو خطر. اتصل بـ999 من مكان آمن لو خدمة الإطفاء لسه ما اتطلبتش.",

    "companionAccount": "حساب المساعد",
    "deleteAccount": "حذف حسابي",
    "deleteAccountWarning": "هيتم حذف بياناتك ومهامك وسجل تدريبك والخزنة الخاصة نهائيًا، وخروجك من كل الأجهزة. مش هتقدر ترجع البيانات بعد الحذف.",
    "confirmAccountName": "اكتب اسم الدخول الموضّح تحت للتأكيد",
    "deleteAccountConfirm": "حذف الحساب نهائيًا",
    "accountNameMismatch": "اكتب اسم الدخول الموضّح فوق، مش اسم البروفايل.",
    "accountDeleted": "تم حذف حسابك.",

    "continueGuest": "دخول كضيف",
    "guestPreview": "معاينة كضيف",
    "guestReadOnly": "للمعاينة بس · أمثلة للمهام والتدريب",
    "guestLabel": "ضيف",
    "exitGuest": "الخروج من المعاينة",
    "guestPrivateDetails": "بيانات الشغل الشخصية ومواعيد الشيفت والحسابات خاصة. سجّل دخولك علشان تشوف بياناتك.",
    "guestPrivateVault": "محتويات الخزنة الخاصة بتظهر بعد تسجيل الدخول بس.",
    "guestShift": "شيفتك في لمحة",
    "guestSchedule": "مواعيد الشيفت الشخصية خاصة",
    "guestTaskOne": "راجع التدريب المطلوب",
    "guestTaskTwo": "اقرأ دليل وجبة الموظف",

    "back": "رجوع",
    "returnCompanion": "الرجوع لمساعد الموظف",
    "logout": "تسجيل الخروج",
    "apiError": "مش قادر أفتح بياناتك دلوقتي. حاول تاني.",
    "tooMany": "محاولات كتير. حاول بعد شوية.",
    "conflict": "نفس البيانات اتعدّلت أثناء كتابتك. راجعها قبل ما تحفظ تاني.",
    "edit": "تعديل",
    "editAccountDetails": "تعديل بيانات الحسابات",
    "workPin": "الرقم السري للشغل",
    "thriveUsername": "اسم المستخدم في THRIVE",
    "importOldVault": "استيراد الخزنة القديمة",
    "importOldIntro": "اكتب كلمة مرور الخزنة القديمة على الجهاز ده لاستيراد محتوياتها. النسخة القديمة هتفضل محفوظة.",
    "oldPassword": "كلمة المرور القديمة",
    "importEntries": "استيراد",
    "importDone": "تم استيراد المحتويات وحفظها.",
    "emptyOldVault": "الخزنة القديمة مفيهاش محتويات.",
    "importFailed": "تعذر فتح الخزنة القديمة. راجع كلمة المرور.",
    "logoutFailed": "تم قفل البيانات هنا. تعذر إكمال تسجيل الخروج؛ حاول تاني.",
    "saveFailed": "تعذر الحفظ. محتوياتك لسه مفتوحة؛ حاول تاني.",
    "invalidEntry": "راجع حجم البيانات المدخلة.",
    "appTitle": "مساعد موظف ويستمورلاند",
    "enterPass": "اكتب كلمة المرور علشان تفتح بياناتك الشخصية.",
    "passphrase": "كلمة المرور",
    "unlock": "فتح",
    "lock": "قفل",
    "fastReference": "مساعد الموظف",
    "findSeconds": "شفتك قدامك.",
    "confirmedOnly": "نفّذ. علّم. لاقي.",
    "emergency": "طوارئ",
    "fire": "حريق",
    "reference": "المرجع",
    "workDetails": "بيانات الشغل",
    "training": "التدريب",
    "accountHelp": "مساعدة الدخول",
    "benefits": "المزايا",
    "uniformDress": "الزي والمظهر",
    "privateVault": "الخزنة الخاصة",
    "backHome": "→ الرئيسية",
    "fireHeadline": "إنذار الحريق: إخلاء",
    "fireIntro": "اخرج من أقرب مخرج حريق. كمّل لنقطة التجمع.",
    "forecourtSafe": "محطة الوقود — لو آمن تعمل كده",
    "fireStep1": "راجع أرضية محل محطة الوقود.",
    "fireStep2": "راجع المخزن.",
    "fireStep3": "راجع الحمامات.",
    "fireStep4": "الموظف المكلّف ياخد جدول العاملين معاه لنقطة التجمع.",
    "onlyIfSafe": "لو ده آمن فقط.",
    "wardenTitle": "مسؤول الحريق — بس لو الدور ده متكلف بيه",
    "warden1": "افحص مكان الحريق لو ده آمن.",
    "warden2": "فعّل أقرب نقطة إنذار يدوية لو لسه ما اتفعّلتش.",
    "warden3": "تعامل بس مع حريق في بدايته، لو آمن وداخل حدود التدريب اللي أخدته من الشركة.",
    "warden4": "ساعد في الإخلاء واتواصل مع المديرين والمشرفين عند نقطة التجمع.",
    "warden5": "امنع أي حد يرجع يدخل المبنى لحد ما خدمة الإطفاء تقول إنه آمن.",
    "warden6": "بلّغ خدمة الإطفاء بمكان وطبيعة الحريق، وأي شخص مش متأكدين من وجوده، وأي مخاطر.",
    "myJob": "شغلي",
    "role": "الوظيفة",
    "roleValue": "عضو فريق – محطة الوقود (ليل)",
    "site": "الموقع",
    "lineManager": "المدير المباشر",
    "managerEmail": "إيميل المدير",
    "colleagueNumber": "رقم الموظف",
    "startDate": "تاريخ البداية",
    "shiftPay": "الشفت والمرتب",
    "regularShifts": "الشفتات الثابتة",
    "shiftTime": "ميعاد الشفت",
    "contractedHours": "الساعات المتعاقد عليها",
    "hourlyRate": "الأجر بالساعة",
    "payFrequency": "الدفع",
    "weekly": "أسبوعي",
    "breakLabel": "البريك",
    "breakValue": "مدفوع",
    "payrollTiming": "مواعيد السنة والدفع",
    "companyYear": "السنة",
    "companyYearValue": "1 أبريل – 31 مارس",
    "payWeekEnds": "نهاية أسبوع الدفع",
    "payWeekEndsValue": "الأحد",
    "payDay": "يوم الدفع",
    "payDayValue": "الجمعة اللي بعده — دفع أسبوعي",
    "kioskSettings": "إعدادات الكشك",
    "kioskId": "رقم الكشك",
    "kioskPin": "الرقم السري",
    "temporaryId": "رقم مؤقت",
    "companyId": "معرّف الشركة",
    "username": "اسم المستخدم",
    "workspace": "مساحة العمل",
    "openPeopleXD": "افتح تطبيق PeopleXD",
    "openThrive": "افتح تطبيق THRIVE",
    "firstDay": "أول يوم / التعريف بالشركة",
    "date": "التاريخ",
    "time": "الوقت",
    "location": "المكان",
    "inductionLocation": "Westmorland Hotel — الاتجاه الشمالي",
    "postcode": "الرمز البريدي",
    "privateCodes": "الأكواد الخاصة",
    "privateCodesNote": "أرقامك وبيانات حساباتك.",
    "openVault": "افتح الخزنة الخاصة",
    "onlineTraining": "التدريب أونلاين",
    "requiredTraining": "التدريبات المطلوبة",
    "essentialLearning": "الأساسي — أولوية حالية",
    "otherAssignedTraining": "تدريبات مطلوبة أخرى",
    "completedLearning": "التدريبات اللي تمت",
    "completed": "تم",
    "course1": "تعريف الزملاء الجدد",
    "course2": "سلامة الغذاء",
    "course3": "الصحة والسلامة",
    "course4": "مراجعة الوعي بالحساسية",
    "completed1": "إجراء وجبات الموظفين",
    "completed2": "الكيك الموسمي الجديد من مطبخ Westmorland – Tebay",
    "completed3": "طريقة استخدام صفحة التعلّم",
    "completed4": "طريقة إضافة المحتوى",
    "completed5": "طريقة استخدام الصفحة الرئيسية والاستكشاف",
    "completed6": "منصة My Westmorland Learn",
    "completed7": "كتيّب مدرسة الطبخ",
    "completed8": "كتيّب المسار الوظيفي",
    "completed9": "خريطة طريق تطوير العمليات",
    "completed10": "قيم عائلة Westmorland",
    "completed11": "قصة Antlers",
    "completed12": "مواقعنا",
    "completed13": "Welcome Antlers – نظرة عامة للموظف",
    "completed14": "حزمة إطلاق «الأكل الجاهز والسلطات» – أكتوبر 2026",
    "course5": "تجربة العميل – طريقة Westmorland",
    "course6": "إجراءات CBE – موظفي محطة الوقود",
    "course7": "منع التحرش الجنسي",
    "peopleAccessTitle": "دخول PeopleXD",
    "usernameRule": "اسم المستخدم",
    "usernameRuleValue": "هو رقم الموظف — 6 أرقام وبيبدأ بـ 0",
    "usernameUnknown": "لو مش فاكره",
    "usernameUnknownValue": "اسأل مديرك المباشر أو ابعت لـ help@mywestmorland.com باسمك الكامل",
    "forgotPassword": "نسيت الباسورد",
    "resetStep1": "افتح mywestmorland.com.",
    "resetStep2": "My Westmorland People ← Forgot Password.",
    "resetStep3": "رقم الموظف + تاريخ الميلاد ← Reset Password.",
    "resetStep4": "افتح إيميل الاسترجاع، أكّد بياناتك وحدد كلمة مرور جديدة.",
    "openResetSite": "افتح صفحة استرجاع PeopleXD",
    "bothForgotten": "نسيت الباسورد وأسئلة الأمان؟",
    "bothForgottenValue": "ابعت لـ help@mywestmorland.com باسمك الكامل. فريق شؤون الموظفين هيعمل إعادة تعيين يدوي.",
    "emailPeopleTeam": "راسل فريق شؤون الموظفين",
    "passwordRules": "شروط الباسورد",
    "passwordRulesValue": "١٢ حرف أو أكتر: حرف كبير، حرف صغير، رقم ورمز.",
    "appFallback": "لو التطبيق مش شغال",
    "appFallbackValue": "استخدم mywestmorland.com للدخول على PeopleXD وحجز الإجازات. لو احتجت، جرّب جهاز محدّث أو لابتوب أو تابلت.",
    "openBrowserPortal": "افتح PeopleXD في المتصفح",
    "uniformTitle": "الزي والملابس",
    "uniformProvided": "الشركة بتوفر",
    "uniformProvidedValue": "معظم الزي المطلوب مجانًا — عادةً تيشيرت أو قميص، مريلة، جاكيت فليس أو بلوفر",
    "ownItems": "عليك أنت عادةً",
    "ownItemsValue": "البنطلون والحذاء، إلا لو حذاء الأمان جزء من معدات الوقاية الشخصية",
    "replacement": "الاستبدال",
    "replacementValue": "مجاني مع الاستهلاك الطبيعي؛ ممكن يتم التحصيل لو التلف أو الاستبدال خارج المعقول",
    "outsideWork": "الشغل بره",
    "outsideWorkValue": "ملابس دافئة ومقاومة للمطر متاحة؛ وفي الصيف ممكن قبعة وواقي شمس",
    "ppeTitle": "معدات الوقاية الشخصية (PPE)",
    "ppeValue": "لو اتسلمت حذاء أمان أو ملابس عالية الوضوح أو أي معدات وقاية شخصية، لازم تلبسها وقت الشغل المطلوب.",
    "appearanceTitle": "المظهر والسلامة",
    "appearance1": "اختار حذاء ثابت، مريح وآمن؛ الشبشب المفتوح أو الكعب العالي غير مناسبين عادةً.",
    "appearance2": "الشعر الطويل يتربط، ويتغطى لو الدور محتاج كده.",
    "appearance3": "الحلق وثقوب الجسم مسموحة عمومًا لو مش مبالغ فيها ومفيش منها خطر سلامة؛ أي وشم مسيء لازم يتغطى.",
    "appearance4": "لو بتتعامل مع أكل: الساعة تتشال، والخاتم يكون سادة فقط.",
    "foodAppearanceTitle": "الأظافر والأكل",
    "foodAppearanceValue": "في تجهيز أو إنتاج الطعام: ممنوع الأظافر الصناعية أو الجِل أو طلاء الأظافر. في أدوار بيع الأكل المغلف مسبقًا فيه مرونة، بشرط تكون الأظافر قصيرة ونظيفة وثابتة ومن غير زينة أو أجزاء ممكن تقع.",
    "uniformPolicyDate": "سياسة الزي والمظهر — تاريخ المراجعة 05/06/2026",
    "benefitsTitle": "مزايا الموظف",
    "mealBenefitTitle": "الأكل أثناء الشغل",
    "mealEntitlement": "الاستحقاق",
    "mealEntitlementValue": "وجبة واحدة لكل فترة راحة في الشفت",
    "freeBreakfast": "فطار مجاني",
    "freeBreakfastValue": "حصة توست، و/أو شوفان أو حبوب إفطار.",
    "freeMeal": "غدا / عشا مجاني",
    "freeMealValue": "شوربة + إما خبز صغير أو ساندوتش مغلف + ثمرة فاكهة",
    "freeDrinks": "مشروبات مجانية",
    "freeDrinksValue": "شاي وقهوة أمريكانو + مياه ومشروبات مركزة من مناطق الموظفين",
    "otherDrinks": "مشروبات تانية",
    "otherDrinksValue": "خصم ٥٠٪ على باقي المشروبات الساخنة والباردة.",
    "mealRulesTitle": "قواعد مهمة للوجبة",
    "mealRule1": "سجّل كل حاجة على الكاشير قبل الأكل أو الخروج، حتى المجاني.",
    "mealRule2": "اشتري من الكاونتر ببطاقة Westmorland Family بتاعتك. ممنوع تخدم نفسك من وراه.",
    "mealRule3": "الوجبة أثناء الشفت. مش للتخزين أو للأخذ للبيت.",
    "mealRule4": "ممنوع الأكل في مناطق تجهيز الطعام، المخازن أو أرضية البيع. الكحول ممنوع.",
    "tebayDiscounts": "خصومات Tebay",
    "ownFood": "منتجات المطابخ والمطابخ السريعة اللي الشركة بتعملها",
    "ownFoodValue": "خصم 75%",
    "otherKitchenItems": "باقي منتجات المطابخ والمطابخ السريعة",
    "otherKitchenItemsValue": "خصم 50%",
    "specialityDrinks": "الشاي والقهوة المتخصصة / الكيك",
    "specialityDrinksValue": "خصم 50%",
    "shopDiscount": "المتجر",
    "shopDiscountValue": "خصم 25% عادةً؛ بعض المنتجات اللي بتتباع كمان في المطابخ ممكن تكون 50% أو 75%",
    "saleClothing": "ملابس عليها تخفيض",
    "saleClothingValue": "خصم 50% من السعر الأصلي",
    "noDiscountTitle": "مفيش خصم على",
    "noDiscountValue": "الوقود، اليانصيب وكروت الخدش، التبغ، الطوابع، معظم السلع المخفضة، عروض شراء عدة قطع، أسطوانات الغاز، PayPoint، وشحن رصيد الموبايل.",
    "hotelCinemaTitle": "الفندق وRheged",
    "hotelRooms": "فندق Westmorland",
    "hotelRoomsValue": "٦٠ جنيه إسترليني للمزدوجة، ٥٠ للفردية، بالإفطار. حتى ٤ ليالي في السنة؛ حجز مسبق وحسب التوفر.",
    "hotelFood": "أكل وشرب الفندق",
    "hotelFoodValue": "خصم 25% للمجموعة حتى 6 أشخاص",
    "cinema": "سينما Rheged",
    "cinemaValue": "دخول مجاني نهارًا ومساءً حسب التوفر. الحجز من شباك التذاكر.",
    "rhegedExtra": "مزايا Rheged",
    "rhegedExtraValue": "دخول المعرض مجانًا + منطقة اللعب الداخلية للأطفال مجانًا حسب التوفر",
    "otherBenefitsTitle": "مزايا تانية",
    "minibus": "الميني باص",
    "minibusValue": "نقل من وإلى الشغل",
    "birthdayLeave": "إجازة عيد الميلاد",
    "birthdayLeaveValue": "يوم إجازة مدفوع",
    "minibusProcedureTitle": "استخدام الميني باص",
    "minibusRule1": "سجّل نفسك كمستخدم للميني باص على My Westmorland People وحدد الخط.",
    "minibusRule2": "لازم تكون في نقطة الركوب المحددة قبل الميعاد؛ الباص مش بيستنى غير دقائق قليلة.",
    "minibusRule3": "لو مش هتحضر الشغل، بلّغ مديرك/الموقع بدري عشان اسمك يتشال من القائمة والسواق يعرف.",
    "minibusRule4": "اربط حزام الأمان طول الرحلة. ممنوع الأكل والشرب والتدخين أو استخدام السجائر الإلكترونية.",
    "minibusRule5": "الميني باص للشغل فقط: من وإلى مكان العمل في الشفتات المجدولة.",
    "minibusRule6": "تغيير نقطة الركوب أو النزول يحتاج استمارة جديدة للمدير؛ تغيير الخط يتم من My Westmorland People.",
    "kendalRouteMap": "افتح خريطة خط كندال",
    "kendalBusContact": "رقم ميني باص كندال",
    "personalNote": "ملاءمة الشفت",
    "nightMinibusNote": "الميني باص مش متاح لنظام شيفتك الحالي.",
    "benefitsPolicyNote": "المزايا والسياسات قابلة للتعديل.",
    "duePrefix": "آخر موعد",
    "daysLeftOne": "فاضل يوم",
    "daysLeftMany": "فاضل {n} أيام",
    "dueToday": "آخر يوم النهارده",
    "overdueOne": "متأخر يوم",
    "overdueMany": "متأخر {n} أيام",
    "openTraining": "افتح تطبيق THRIVE",
    "resetChecklist": "ابدأ من جديد",
    "vaultNote": "أرقام وملاحظات خاصة.",
    "addPrivateEntry": "أضف بيانات خاصة",
    "home": "الرئيسية",
    "fireNav": "حريق",
    "detailsNav": "بياناتي",
    "trainingNav": "تدريب",
    "privateEntry": "بيانات خاصة",
    "label": "الاسم",
    "value": "القيمة",
    "noteOptional": "ملاحظة (اختياري)",
    "cancel": "إلغاء",
    "save": "حفظ",
    "noPrivateEntries": "مفيش بيانات خاصة لسه.",
    "reveal": "إظهار",
    "hide": "إخفاء",
    "copy": "نسخ",
    "copied": "اتنسخ",
    "delete": "حذف",
    "deleteConfirm": "تحذف البيانات دي؟",
    "wrongPass": "راجع بيانات الدخول.",
    "online": "متصل",
    "offline": "غير متصل · اتصل بالإنترنت لفتح الموقع",
    "ready": "جاهز",
    "nowTitle": "المهم لشفتك",
    "myShift": "شفتّي",
    "nextLearning": "التدريب الجاي",
    "allReference": "كل المراجع",
    "myTasks": "مهامي",
    "shiftDutiesTitle": "مهام الوردية",
    "shiftDutiesNav": "الوردية",
    "shiftDutyNightLabel": "وردية",
    "shiftArrival": "الوصول إلى العمل",
    "shiftDeparture": "المغادرة",
    "shiftDutyAdd": "+ إضافة",
    "shiftDutyPlaceholder": "اكتب المهمة",
    "shiftDutyTimeOptional": "وقت اختياري",
    "shiftDutyTonight": "الليلة دي بس",
    "shiftDutyEmpty": "مفيش مهام إضافية",
    "shiftDutyEdit": "تعديل المهمة",
    "shiftDutyDelete": "حذف المهمة",
    "shiftDutyDeleteConfirm": "تحذف المهمة دي؟",
    "myProfile": "بياناتي",
    "fireQuick": "الحريق والإخلاء",
    "quickAction": "تصرف سريع",
    "peopleXDRecoveryAction": "مشكلة في دخول PeopleXD",
    "mealAction": "وجبة الموظف",
    "mealRuleAction": "سجّلها على الكاشير",
    "evacuationExit": "اخرج من أقرب مخرج حريق.",
    "evacuationAssembly": "كمّل لنقطة التجمع.",
    "add": "إضافة",
    "addTask": "مهمة واحدة…",
    "newShift": "ابدأ شفت جديد",
    "findReference": "بتدور على إيه؟",
    "otherAccount": "حساب تاني",
    "ownerAccount": "حسابي الحالي",
    "createAccount": "إنشاء حساب",
    "recoverAccount": "استرجاع الحساب",
    "accountName": "اسم المستخدم",
    "accountNameHint": "من ٣ إلى ٤٠ حرف إنجليزي أو رقم؛ مسموح بالنقطة والشرطة.",
    "newPasswordHint": "استخدم حرفين أو رقمين على الأقل.",
    "accountUnavailable": "اسم المستخدم ده مش متاح.",
    "recoveryCode": "كود الاسترجاع",
    "keepRecovery": "احتفظ بالكود في مكان آمن. هتحتاجه لو نسيت كلمة المرور.",
    "done": "تم",
    "displayName": "الاسم",
    "manager": "المدير",
    "hours": "ساعات الأسبوع",
    "paidBreak": "الراحة",
    "annualHoliday": "الإجازة السنوية بالأيام",
    "minibusNote": "ملاحظة المواصلات",
    "shiftStart": "بداية الشفت",
    "shiftEnd": "نهاية الشفت",
    "shiftDays": "أيام الشفت",
    "hoursUnit": "ساعة",
    "addCourse": "إضافة كورس",
    "courseTitle": "اسم الكورس",
    "arabicTitleOptional": "الاسم بالعربي (اختياري)",
    "dueDate": "آخر موعد",
    "progressLabel": "التقدم",
    "notStarted": "لسه مبدأتش",
    "inProgress": "شغّال عليه",
    "optionalLearning": "اختياري",
    "learningClear": "خلصت المطلوب",
    "myProgress": "اختار كورس وكمّل",
    "addFirstTask": "أضف مهمة وابدأ قائمتك.",
    "deleteTaskConfirm": "تشيل المهمة دي؟",
    "deleteCourseConfirm": "تشيل الكورس ده من قائمتك؟",
    "grossEstimate": "أجر الأسبوع قبل الخصم (تقديري)",
    "firstDayTime": "وقت الحضور",
    "firstDayLocation": "مكان الحضور",
    "firstDayPostcode": "الرمز البريدي",
    "courseCount": "{n} كورسات",
    "myLearning": "قائمتي",
    "newIncident": "موقف جديد",
    "mealsTab": "الوجبات",
    "discountsTab": "الخصومات",
    "travelTab": "مزايا أخرى",
    "leisureTab": "الترفيه",
    "dailyTab": "في الشغل",
    "foodTab": "التعامل مع الأكل",
    "issuedTab": "الزي",
    "resetTab": "استرجاع الباسورد",
    "usernameTab": "اسم المستخدم",
    "appTab": "مساعدة التطبيق",
    "shiftTab": "الشفت والمرتب",
    "accountsTab": "الحسابات",
    "arrivalTab": "أول يوم",
    "privateDataError": "بياناتك مش متاحة دلوقتي. حاول تاني.",
    "sessionError": "الدخول مكملش. حاول تاني.",
    "mealSandwiches": "المجاني هو الساندوتش المغلّف فقط. باقي الساندوتشات واللفائف والخبز المسطّح والتوست والبانيني: خصم حتى ٧٥٪.",
    "adultMealRule": "خصم الوجبات ٧٥٪ لوجبات الكبار فقط.",
    "pendingTab": "المطلوب",
    "retry": "حاول تاني",
    "retryIntro": "حاول فتح بياناتك تاني."
  },
  "en": {
    "faTitle": "First aid",
    "faHint": "CPR · choking · injuries",
    "faCall": "Call 999",
    "faEmergency": "Life-threatening emergency? Call 999. Put your phone on speaker and follow the call handler.",
    "faCprTab": "Unresponsive / CPR",
    "faChokeTab": "Choking",
    "faRecoveryTab": "Breathing normally",
    "faInjuriesTab": "Bleeding / injuries",
    "faAdult": "Adult guidance. For a child or baby, call 999 and follow age-specific instructions.",
    "faCprTitle": "Unresponsive and not breathing normally",
    "faCheckTitle": "Check danger and response",
    "faCheck": "Make sure it is safe to approach. Speak to them and gently tap their shoulders. Shout for help.",
    "fa999Title": "No response? Call 999 now",
    "fa999": "Use speakerphone. Open the airway with a head tilt and chin lift; check breathing with the call handler. Gasping is not normal breathing.",
    "faPressTitle": "No normal breathing? Start CPR",
    "faPress": "Hands together in the centre of the chest, arms straight. Press 5–6 cm at 100–120 a minute; let the chest fully rise between presses.",
    "faBreaths": "If trained, able and willing: 30 presses, then 2 breaths. Otherwise keep giving chest compressions. Follow 999.",
    "faContinue": "Continue until professionals take over or tell you to stop, normal breathing/signs of life return, or you cannot continue. Pause when the AED tells you.",
    "faAedTitle": "Use an AED as soon as it arrives",
    "faAed": "Send a helper for the AED; 999 can guide them to it. Do not leave the person alone to search. Switch it on and follow its prompts; apply pads to bare skin as shown.",
    "faAedClear": "Keep compressions going while a helper fits pads. Nobody touches the person during analysis or a shock. Restart CPR immediately when instructed, even if no shock is advised.",
    "faChildAed": "AEDs can be used on children. Use child mode/pads when available and follow 999 and device instructions; do not delay because only adult mode is available.",
    "faRecoveryTitle": "Unresponsive but breathing normally",
    "faRecoveryWarning": "Call 999 and keep watching breathing. After trauma or suspected neck/back injury, avoid moving them; follow 999 to keep the airway open. Gasping needs CPR, not the recovery position.",
    "faRecovery1": "If there is no trauma: place the near arm at a right angle, palm up. Hold the back of the other hand against the cheek nearest you.",
    "faRecovery2": "Bend the far knee with the foot on the ground. Keep the hand against the cheek and gently roll them towards you onto their side.",
    "faRecovery3": "Bend the top leg to steady them. Tilt the head back and lift the chin to keep the airway open. Stay with them; if normal breathing stops, start CPR.",
    "faChokeTitle": "Adult choking",
    "faCoughTitle": "Can cough strongly? Encourage coughing",
    "faCough": "Stay with them. If they can cough effectively, do not give back blows or thrusts. If they cannot speak, breathe or cough effectively, act immediately.",
    "faBackTitle": "Up to 5 back blows",
    "faBack": "Ask someone to call 999. Stand slightly behind and to one side. Support the chest, lean them forward and give sharp blows between the shoulder blades with the heel of your hand. Check after each.",
    "faThrustTitle": "Still blocked? Up to 5 abdominal thrusts",
    "faThrust": "Stand behind, arms around the waist. Put a fist above the navel and below the ribs, hold it with your other hand and pull sharply inwards and upwards.",
    "faChokeNext": "If still blocked, ensure 999 has been called and alternate up to 5 back blows and 5 thrusts. Stop when cleared. If they become unresponsive, start CPR and follow 999.",
    "faChokeWarning": "Do not put fingers into the mouth unless you can see the object. Do not use abdominal thrusts on pregnant people or babies; ask 999 for the appropriate technique.",
    "faChokeAfter": "After abdominal thrusts, get medical assessment even if the blockage clears.",
    "faBleedTitle": "Heavy or uncontrolled bleeding",
    "faBleed1": "Call 999 for severe bleeding. Wear gloves if available. Press firmly on the wound with a clean cloth or dressing.",
    "faBleed2": "Do not remove an embedded object or press on it; press either side. If blood soaks through, add another dressing on top and keep pressure.",
    "faShock": "Cold, clammy skin, weakness, confusion or faintness after injury can be shock. Call 999, keep them warm, monitor breathing and give no food or drink. Avoid moving injured limbs.",
    "faCutsTitle": "Small cuts and grazes",
    "faCuts": "Once bleeding stops: clean hands, rinse the wound with clean tap/bottled water and cover with a sterile dressing. Do not put alcohol or antiseptic inside it. Get 111 advice for dirt that remains, infection signs or bites.",
    "faBonesTitle": "Possible fracture or head injury",
    "faBones": "Support the injured part as found; do not straighten it or put weight on it. Arrange urgent medical assessment. For a suspected neck/back injury, keep them still and call 999.",
    "faHead": "After a head injury, call 999 for failure to wake, difficulty staying awake, a seizure, or new problems with speech, balance or movement. For vomiting, dizziness or other concerns, seek urgent 111 advice. Do not leave them alone.",
    "faSprainTitle": "Minor sprain or strain",
    "faSprain": "Protect and rest it. Use an ice pack wrapped in a towel for up to 20 minutes every 2–3 hours; never directly on skin. Support and raise it if comfortable. Get medical help for severe pain, deformity, numbness or inability to bear weight.",
    "faBurnLink": "Burns: open the cooling checklist",
    "faReportLink": "Once safe: report the incident",
    "faHelpLink": "Someone injured? Open first aid",
    "faWorkTitle": "Before your shift",
    "faWork": "Check who the first aiders are, where the kit and AED are, and how to summon help at your site. Ask your manager if unsure.",
    "faSources": "Sources and scope",
    "faSourceNote": "Quick adult reference, not a first-aid qualification. Reviewed against UK guidance on 9 October 2026. Follow 999 and your workplace arrangements.",
    "incidentTitle": "Report an accident or near miss",
    "incidentQuick": "Accident or near miss?",
    "homeHazardTitle": "Safety concern or hazard?",
    "homeHazardHint": "Check the risk and inform your manager",
    "incidentQuickHint": "Injury or near miss · act and report",
    "incidentIntro": "Even if nobody is hurt, report a near miss so the same hazard does not cause an injury.",
    "incidentClassifyTitle": "Identify the event",
    "incidentNearTitle": "Near miss",
    "incidentNearDesc": "Something happened that could have caused injury or damage, but no harm occurred.",
    "incidentAccidentTitle": "Accident",
    "incidentAccidentDesc": "Injury or damage did occur. Get appropriate help and report the incident.",
    "incidentStepsTitle": "Five steps: respond and report",
    "incidentStep1Title": "Make the area safe",
    "incidentStep1Desc": "Check immediate hazards. Remove them only if safe and within your training; otherwise keep people away and report.",
    "incidentStep2Title": "Check everyone is safe",
    "incidentStep2Desc": "Check those involved and arrange first aid or emergency assistance if needed.",
    "incidentStep3Title": "Tell your manager",
    "incidentStep3Desc": "Report when, where, who was involved or witnessed it, and what happened.",
    "incidentStep4Title": "Log the incident",
    "incidentStep4Desc": "Use the company reporting system. Choose the correct site and incident type.",
    "incidentStep5Title": "Prevent it happening again",
    "incidentStep5Desc": "Review the cause with your manager and follow through on controls to prevent a repeat.",
    "incidentRecordTitle": "Information to record",
    "incidentRecordWhen": "When — date and time",
    "incidentRecordWhere": "Where — exact location",
    "incidentRecordWho": "Who — people involved and witnesses",
    "incidentRecordWhat": "What — the task and what happened",
    "incidentAlertTitle": "Reporting in Alert65",
    "incidentAlertIntro": "The company training video shows this route:",
    "incidentAlertSelect": "Select the correct group and site, then incident type. Near miss is a separate option from Accident.",
    "incidentAlertSave": "Complete the required fields for that type and confirm submission; saving alone is not proof of submission.",
    "incidentAlertNote": "The screenshots show an Accident example at Cairn Lodge. Do not copy that site or choose Accident for a near miss.",
    "incidentEscalate": "In immediate danger or serious injury, prioritise safety and urgent help over completing a form.",
    "riskQuickTitle": "Assess risk before the task",
    "riskQuickIntro": "A hazard can cause harm. Risk considers how likely harm is and how severe it could be.",
    "riskStep1Title": "Identify",
    "riskStep1Desc": "What is the hazard, and who could be harmed?",
    "riskStep2Title": "Assess",
    "riskStep2Desc": "Consider likelihood and severity; prioritise the highest risks.",
    "riskStep3Title": "Control",
    "riskStep3Desc": "Remove or reduce the hazard before relying on PPE.",
    "riskOrderTitle": "Hierarchy of risk controls",
    "riskOrderIntro": "Start with the strongest control. PPE is the last line of defence.",
    "riskOrder1": "Eliminate the hazard",
    "riskOrder2": "Substitute a safer option",
    "riskOrder3": "Isolate it with engineering controls",
    "riskOrder4": "Use safer work practices and instructions",
    "riskOrder5": "Use personal protective equipment (PPE)",
    "riskReportLink": "Accident or near miss? Open the reporting steps",
    "knifeGuideTitle": "Use knives safely",
    "knifeGuide1": "Before use: choose a suitable knife and check that it is sharp and in good condition.",
    "knifeGuide2": "When carrying it, keep the blade tip down at your side, not upwards or forwards.",
    "conflictGuideTitle": "If someone becomes aggressive",
    "conflictGuide1": "Speak calmly and clearly. Listen and show concern without escalating or confronting.",
    "conflictGuide2": "Move to safety and get help if threatened. Report violence or threats at work.",
    "loneGuideTitle": "Working alone — before your shift",
    "loneGuide1": "Know the agreed check-in arrangements, who monitors your safety and how to contact them or raise an alarm. Ask which tasks you must not do alone.",
    "loneGuide2": "If you feel unsafe, cannot reach support or face aggression, withdraw if safe and follow your site's emergency plan. Call 999 for immediate danger.",
    "dseGuideTitle": "Screen work — comfortable setup",
    "dseGuide1": "Keep the screen in front of you, about an arm's length away, with its top at eye level. Support your lower back, relax your shoulders and keep forearms roughly horizontal.",
    "dseGuide2": "Reduce glare, keep leg space clear, and take regular short breaks or changes of task. Report persistent pain or unsuitable equipment.",

    "ppeActionLink": "Open PPE safety checks",
    "poisonQuick": "Cleaning chemical swallowed",
    "poisonQuickHint": "Act immediately if poisoning is suspected",
    "ppeActionHeading": "Before using protective equipment",
    "ppeActionCheck": "Know which PPE the task requires and how to use it.",
    "ppeActionFault": "Inspect it. If missing or damaged, do not start the task; tell your supervisor.",
    "ppeActionWear": "Wear it even for short jobs; clean and store it as instructed.",
    "signGuideHeading": "Recognise safety signs",
    "signGuideHint": "Use colour and shape as clues; follow the symbol on each sign.",
    "sign_red_title": "Prohibited",
    "sign_red_detail": "e.g. no entry",
    "sign_yellow_title": "Warning",
    "sign_yellow_detail": "Take precautions",
    "sign_blue_title": "Mandatory",
    "sign_blue_detail": "Follow the instruction",
    "sign_green_title": "Emergency & first aid",
    "sign_green_detail": "Exits and first-aid points",
    "poisonTitle": "If someone swallows a cleaning chemical",
    "poisonAction": "Get medical help immediately: call 999 or go to A&E. Do not induce vomiting or give food or drink. Take the product container or safety data sheet if available without delaying help.",
    "poisonNHS": "NHS poisoning guidance",
    "fireGuideLabel": "QUICK RESPONSE GUIDE",
    "firePriorityLabel": "ALWAYS THE PRIORITY",
    "fireDiscoveredTitle": "If you discover a fire",
    "fireEvacTitle": "When the fire alarm sounds",
    "fireChecklistHint": "For rehearsal and review only. In a fire, evacuate without stopping to tick boxes.",
    "fireEvacuateNotice": "When the alarm sounds, start evacuating immediately. Do not delay to read this page.",
    "firePracticeTitle": "Evacuation practice checklist",
    "firePracticeHint": "For drills or review only — not during a fire",
    "fireEquipmentToggleHint": "5 types · open reference",
    "fireCall999": "From safety: call 999 if not already called",
    "fireGuidanceTitle": "While leaving and once outside",
    "fireNoReturnTitle": "Do not go back inside",
    "fireUnsafeTitle": "If fire or smoke increases",
    "fireReportTitle": "Report from a safe place",
    "fireRolesTitle": "Additional duties by role",
    "fireRolesIntro": "Your evacuation comes first. Never enter an unsafe area just to complete a check.",
    "fireForecourtHint": "Check the listed areas only if safe.",
    "fireWardenHint": "Only for staff assigned this role.",
    "fireReferenceTitle": "Recognise fire-fighting equipment",
    "fireReferenceIntro": "A quick guide to identification, not a substitute for site training.",

    "extVisualTitle": "Identify extinguisher types",
    "extVisualWarning": "Training reference only: evacuate first. Only trained, authorised staff with a safe escape route may consider using an extinguisher. Read the actual unit label.",
    "extVisualNote": "Colours illustrate common extinguisher identification, not verified equipment at this workplace. Check the label and fire plan.",
    "chemicalVisualTitle": "Check the actual cleaning product label",
    "chemicalVisualNote": "Verify product name, code and PPE against the workplace label and safety data sheet. No D10 product has been confirmed yet.",

    "safetyQuick": "Workplace safety",
    "safetyQuickHint": "Burns · hazards · lifting · substances",
    "burnTab": "Burns",
    "hazardTab": "Hazards",
    "liftingTab": "Lifting",
    "substanceTab": "Substances",
    "burnTitle": "Heat burns & scalds",
    "burn1": "Cool the area under cool running water for 20 minutes.",
    "burn2": "Remove nearby clothing and jewellery; leave anything stuck to the burn.",
    "burn3": "After cooling, lay clean cling film over it; do not wrap it around the limb or put it on the face.",
    "burn4": "Do not apply ice, creams, oils or butter. Keep the rest of the body warm and get help from the site first aider.",
    "burnUrgentTitle": "Urgent medical help",
    "burnUrgent": "Call 999 or get help reaching A&E for large or deep burns, burns to the face, genitals or bottom, or electrical or chemical burns. If unsure, get advice from NHS 111.",
    "burnScope": "These steps cover heat burns and scalds. Chemical exposure needs separate instructions.",
    "nhsBurnGuide": "NHS burns guidance",
    "hazardTitle": "A hazard or faulty equipment",
    "hazard1": "Stop if the task is unsafe. Tell the supervisor immediately what and where the hazard is.",
    "hazard2": "Do not use faulty equipment, or new equipment without training and instructions.",
    "hazard3": "If a reported problem remains, follow up with the manager; reporting does not mean it has been fixed.",
    "wetFloorTitle": "A spill or unsafe route",
    "wetFloor1": "Keep routes clear of clutter and cables. Report damaged floors or mats.",
    "wetFloor2": "Clean ordinary spills promptly if trained and safe; dry the area and use a wet-floor sign while it is wet.",
    "wetFloor3": "Fuel, chemicals or an unknown substance? Keep people away and tell the supervisor; follow the site’s specific procedure.",
    "liftingTitle": "Before lifting or moving a load",
    "lifting1": "Assess the load, route and your ability. If too heavy or hard to grip, stop and get help or suitable handling equipment.",
    "lifting2": "Stand firmly, keep the load close, bend your knees and keep a natural back posture. Lift smoothly as you straighten your legs.",
    "lifting3": "Keep the heavier side close to your body. Turn with your feet instead of twisting your back, and keep your view clear.",
    "lifting4": "Set it down carefully. Use a suitable trolley for longer distances; prefer pushing when safe and appropriate for the equipment.",
    "substanceTitle": "Before handling a hazardous substance",
    "substance1": "Check the label, safe working instructions and the product’s COSHH assessment. If instructions or training are missing, ask the supervisor before use.",
    "substance2": "Use the controls and protective equipment specified for the task. A hazard symbol alone does not identify the protection needed.",
    "substance3": "Watch for dust, fumes and gases, not just containers. Exposure can occur through breathing, swallowing, skin or eyes, or a puncture wound.",
    "substance4": "A spill or exposure? Stop the task, move away from danger and alert the supervisor. Follow the substance-specific emergency instructions.",
    "fireRaise": "Found a fire? Shout “Fire!”, raise the nearest alarm if safe, then leave.",
    "fireLeave": "Do not run, use lifts or return for belongings. Do not re-enter until authorised.",
    "fireStop": "Fire spreading or heat reaching you? Stop tackling it and leave immediately. Stay low if there is smoke as you escape.",
    "firePassTitle": "Extinguisher — only if trained and authorised",
    "firePassGuard": "Only for a small fire, with a suitable extinguisher and a safe escape route. If uncomfortable, leave.",
    "firePass": "PASS: Pull the pin · Aim at the base from a safe distance · Squeeze the handles · Sweep side to side.",
    "fireContact": "Tell the fire warden the location, anyone missing and any hazards. Call 999 from safety if the Fire Service has not been called.",

    "companionAccount": "Companion account",
    "deleteAccount": "Delete my account",
    "deleteAccountWarning": "This permanently deletes your profile, tasks, training records and Private Vault, and signs you out on every device. This cannot be undone.",
    "confirmAccountName": "Type the sign-in username shown below",
    "deleteAccountConfirm": "Permanently delete account",
    "accountNameMismatch": "Enter the sign-in username shown above, rather than your profile name.",
    "accountDeleted": "Your account has been deleted.",

    "continueGuest": "Continue as guest",
    "guestPreview": "Guest preview",
    "guestReadOnly": "Read only · Sample tasks and training",
    "guestLabel": "Guest",
    "exitGuest": "Exit guest preview",
    "guestPrivateDetails": "Personal details, schedules and account information stay private. Sign in to view your own.",
    "guestPrivateVault": "Private Vault contents are only available after sign-in.",
    "guestShift": "Your shift, at a glance",
    "guestSchedule": "Personal schedules stay private",
    "guestTaskOne": "Review required training",
    "guestTaskTwo": "Read the colleague meal guide",

    "back": "Back",
    "returnCompanion": "Return to Staff Companion",
    "logout": "Sign out",
    "apiError": "Unable to open your information. Please try again.",
    "tooMany": "Too many attempts. Please try again later.",
    "conflict": "This item changed while you were editing. Review it before saving again.",
    "edit": "Edit",
    "editAccountDetails": "Edit account details",
    "workPin": "Work PIN",
    "thriveUsername": "THRIVE username",
    "importOldVault": "Import old vault",
    "importOldIntro": "Enter the old vault password for this device to import its entries. The old copy will be kept.",
    "oldPassword": "Old password",
    "importEntries": "Import",
    "importDone": "Entries imported and saved.",
    "emptyOldVault": "The old vault has no entries.",
    "importFailed": "Unable to open the old vault. Check its password.",
    "logoutFailed": "Information is locked here. Sign out could not finish; please try again.",
    "saveFailed": "Unable to save. Your entries are still open; please try again.",
    "invalidEntry": "Check the size of the information entered.",
    "appTitle": "WF Staff Companion",
    "enterPass": "Enter your password to open your personal information.",
    "passphrase": "Password",
    "unlock": "Unlock",
    "lock": "Lock",
    "fastReference": "Staff companion",
    "findSeconds": "Your shift, at a glance.",
    "confirmedOnly": "Act. Check. Find.",
    "emergency": "Emergency",
    "fire": "Fire",
    "reference": "Reference",
    "workDetails": "Work details",
    "training": "Training",
    "accountHelp": "Account help",
    "benefits": "Benefits",
    "uniformDress": "Uniform & dress",
    "privateVault": "Private vault",
    "backHome": "← Home",
    "fireHeadline": "Fire alarm — evacuate",
    "fireIntro": "Use the nearest fire exit. Continue to the Assembly Point.",
    "forecourtSafe": "Forecourt — if safe to do so",
    "fireStep1": "Check Forecourt shop floor.",
    "fireStep2": "Check storeroom.",
    "fireStep3": "Check toilets.",
    "fireStep4": "Delegated team member takes the rota to the Assembly Point.",
    "onlyIfSafe": "Only if safe to do so.",
    "wardenTitle": "Fire Warden — only if you are assigned this role",
    "warden1": "Investigate the fire scene only if safe.",
    "warden2": "Activate the nearest break-glass point if not already done.",
    "warden3": "Tackle only an early-stage fire, only if safe and within company training.",
    "warden4": "Assist evacuation and liaise with managers/supervisors at the Assembly Point.",
    "warden5": "Prevent re-entry until the Fire Service says it is safe.",
    "warden6": "Brief the Fire Service on fire location/nature, anyone unaccounted for and hazards.",
    "myJob": "My job",
    "role": "Role",
    "roleValue": "Team Member – Filling Station (Nights)",
    "site": "Site",
    "lineManager": "Line manager",
    "managerEmail": "Manager email",
    "colleagueNumber": "Colleague number",
    "startDate": "Start date",
    "shiftPay": "Shift & pay",
    "regularShifts": "Regular shifts",
    "shiftTime": "Shift time",
    "contractedHours": "Contracted hours",
    "hourlyRate": "Hourly rate",
    "payFrequency": "Pay frequency",
    "weekly": "Weekly",
    "breakLabel": "Break",
    "breakValue": "Paid",
    "payrollTiming": "Year & payroll timing",
    "companyYear": "Year",
    "companyYearValue": "1 April – 31 March",
    "payWeekEnds": "Pay week closes",
    "payWeekEndsValue": "Sunday",
    "payDay": "Pay day",
    "payDayValue": "Following Friday — paid weekly",
    "kioskSettings": "Kiosk settings",
    "kioskId": "Kiosk ID",
    "kioskPin": "PIN",
    "temporaryId": "Temporary ID",
    "companyId": "Company ID",
    "username": "Username",
    "workspace": "Workspace",
    "openPeopleXD": "Open PeopleXD app",
    "openThrive": "Open THRIVE app",
    "firstDay": "First day / induction",
    "date": "Date",
    "time": "Time",
    "location": "Location",
    "inductionLocation": "Westmorland Hotel, Northbound",
    "postcode": "Postcode",
    "privateCodes": "Private codes",
    "privateCodesNote": "Your codes and account details.",
    "openVault": "Open Private Vault",
    "onlineTraining": "Online training",
    "requiredTraining": "Required training",
    "essentialLearning": "Essential Learning — current priority",
    "otherAssignedTraining": "Other assigned training",
    "completedLearning": "Completed learning",
    "completed": "Completed",
    "course1": "Welcome Antlers – Colleague Induction",
    "course2": "Food Safety Training",
    "course3": "Health & Safety Training",
    "course4": "Allergy Awareness Recap",
    "completed1": "Colleague Meal Procedure",
    "completed2": "NEW Seasonal Cakes from Westmorland Kitchen – Tebay…",
    "completed3": "How to… Learn Page",
    "completed4": "How to… Add Content",
    "completed5": "How to… Homepage & Explore",
    "completed6": "My Westmorland Learn",
    "completed7": "Cookery School Booklet",
    "completed8": "Careers Book",
    "completed9": "Ops Development Road Map",
    "completed10": "Our Family Values",
    "completed11": "Our Antlers Story",
    "completed12": "Our sites",
    "completed13": "Welcome Antlers – Colleague Overview",
    "completed14": "Launch Pack 'Food To Go' & 'Salads' Oct 26",
    "course5": "Customer Experience – The Westmorland Way",
    "course6": "CBE Procedures – Filling Station Colleagues",
    "course7": "Prevention of Sexual Harassment",
    "peopleAccessTitle": "PeopleXD access",
    "usernameRule": "Username",
    "usernameRuleValue": "Your colleague number — 6 digits and starts with 0",
    "usernameUnknown": "If you do not know it",
    "usernameUnknownValue": "Ask your line manager or email help@mywestmorland.com with your full name",
    "forgotPassword": "Forgot password",
    "resetStep1": "Open mywestmorland.com.",
    "resetStep2": "My Westmorland People → Forgot Password.",
    "resetStep3": "Colleague number + date of birth → Reset Password.",
    "resetStep4": "Open the reset email. Confirm your details and set a new password.",
    "openResetSite": "Open PeopleXD reset page",
    "bothForgotten": "Forgot password and security questions?",
    "bothForgottenValue": "Email help@mywestmorland.com with your full name. The People Team will manually reset access.",
    "emailPeopleTeam": "Email People Team",
    "passwordRules": "Password rules",
    "passwordRulesValue": "12+ characters: uppercase, lowercase, number and symbol.",
    "appFallback": "If the app is not working",
    "appFallbackValue": "Use mywestmorland.com for PeopleXD, including holiday booking. If needed, try an updated device, laptop or tablet.",
    "openBrowserPortal": "Open PeopleXD in browser",
    "uniformTitle": "Uniform & dress",
    "uniformProvided": "Company provides",
    "uniformProvidedValue": "Most required uniform free of charge — typically T-shirts/shirts, aprons, fleeces or jumpers",
    "ownItems": "Usually your own",
    "ownItemsValue": "Trousers and footwear, unless safety footwear is issued as PPE",
    "replacement": "Replacement",
    "replacementValue": "Normally free for reasonable wear and tear; charges may apply beyond that",
    "outsideWork": "Outdoor work",
    "outsideWorkValue": "Warm and waterproof clothing is provided; hats and sunscreen may also be available in summer",
    "ppeTitle": "PPE",
    "ppeValue": "If safety footwear, high-vis or other PPE is issued for your role, it must be worn when required.",
    "appearanceTitle": "Appearance & safety",
    "appearance1": "Wear sturdy, comfortable and safe footwear; flip-flops and high heels are normally unsuitable.",
    "appearance2": "Tie back long hair and cover it where required.",
    "appearance3": "Piercings are generally acceptable if not excessive or a safety risk; offensive tattoos must be covered.",
    "appearance4": "When working with food, remove watches and wear only a plain ring.",
    "foodAppearanceTitle": "Nails & food work",
    "foodAppearanceValue": "Food preparation/production: no false nails, gel nails or nail varnish. Pre-packed food retail has some flexibility, but nails must be short, clean, secure and free from jewels or loose additions.",
    "uniformPolicyDate": "Uniform & Dress Policy — review date 05/06/2026",
    "benefitsTitle": "Staff benefits",
    "mealBenefitTitle": "Meals at work",
    "mealEntitlement": "Entitlement",
    "mealEntitlementValue": "One meal entitlement per break in your shift",
    "freeBreakfast": "Free breakfast",
    "freeBreakfastValue": "One portion of toast and/or either porridge or cereal.",
    "freeMeal": "Free lunch / evening meal",
    "freeMealValue": "Soup + either a bread roll or boxed/wrapped sandwich + one piece of fruit",
    "freeDrinks": "Free drinks",
    "freeDrinksValue": "Tea and Americano + water and cordials from colleague areas",
    "otherDrinks": "Other drinks",
    "otherDrinksValue": "50% off other hot and cold drinks.",
    "mealRulesTitle": "Meal rules",
    "mealRule1": "Record every item at the till before eating or leaving — including free items.",
    "mealRule2": "Buy at the counter using your Westmorland Family Card. No self-service behind the counter.",
    "mealRule3": "Eat during your shift. No saving items for later or taking them home.",
    "mealRule4": "No eating in food-preparation areas, stock rooms or on the sales floor. No alcohol.",
    "tebayDiscounts": "Tebay discounts",
    "ownFood": "Kitchens / Quick Kitchens items made by the company",
    "ownFoodValue": "75% off",
    "otherKitchenItems": "Other Kitchens / Quick Kitchens items",
    "otherKitchenItemsValue": "50% off",
    "specialityDrinks": "Speciality teas & coffees / cakes",
    "specialityDrinksValue": "50% off",
    "shopDiscount": "Shops",
    "shopDiscountValue": "Usually 25% off; items also sold in Kitchens may qualify for 50% or 75%",
    "saleClothing": "Clothing reduced in a sale",
    "saleClothingValue": "50% off the original selling price",
    "noDiscountTitle": "No discount on",
    "noDiscountValue": "Fuel, lottery/scratch cards, tobacco, stamps, most reduced items, multi-buy promotions, gas cylinders, PayPoint and mobile top-ups.",
    "hotelCinemaTitle": "Hotel & Rheged",
    "hotelRooms": "Westmorland Hotel",
    "hotelRoomsValue": "£60 double/twin · £50 single · breakfast included. Up to 4 nights/year; advance booking, subject to availability.",
    "hotelFood": "Hotel food & drink",
    "hotelFoodValue": "25% off the total bill for groups up to 6",
    "cinema": "Rheged cinema",
    "cinemaValue": "Free daytime/evening entry, subject to availability. Book at the box office.",
    "rhegedExtra": "Rheged extras",
    "rhegedExtraValue": "Free Gallery entry + free indoor play for children, subject to availability",
    "otherBenefitsTitle": "Other benefits",
    "minibus": "Minibus",
    "minibusValue": "Transport to and from work",
    "birthdayLeave": "Birthday leave",
    "birthdayLeaveValue": "One paid day off",
    "minibusProcedureTitle": "Using the minibus",
    "minibusRule1": "Register as a minibus user in My Westmorland People and select the route you need.",
    "minibusRule2": "Be at the designated pick-up point before the stated time; the bus only waits a few minutes.",
    "minibusRule3": "If you will not attend work, tell your manager/site in advance so the driver can be informed and your name removed.",
    "minibusRule4": "Wear a seat belt at all times. No food/drink, smoking or vaping.",
    "minibusRule5": "The minibus is only for travel to and from work on scheduled shifts.",
    "minibusRule6": "Change of pick-up/drop-off needs a new form to your manager; route changes are requested in My Westmorland People.",
    "kendalRouteMap": "Open Kendal route map",
    "kendalBusContact": "Kendal bus contact",
    "personalNote": "Shift applicability",
    "nightMinibusNote": "Minibus unavailable for your current shift pattern.",
    "benefitsPolicyNote": "Benefits and policies may be amended.",
    "duePrefix": "Due",
    "daysLeftOne": "1 day left",
    "daysLeftMany": "{n} days left",
    "dueToday": "Due today",
    "overdueOne": "1 day overdue",
    "overdueMany": "{n} days overdue",
    "openTraining": "Open THRIVE app",
    "resetChecklist": "Reset checks",
    "vaultNote": "Private codes and notes.",
    "addPrivateEntry": "Add private entry",
    "home": "Home",
    "fireNav": "Fire",
    "detailsNav": "Details",
    "trainingNav": "Training",
    "privateEntry": "Private entry",
    "label": "Label",
    "value": "Value",
    "noteOptional": "Note (optional)",
    "cancel": "Cancel",
    "save": "Save",
    "noPrivateEntries": "No private entries yet.",
    "reveal": "Reveal",
    "hide": "Hide",
    "copy": "Copy",
    "copied": "Copied",
    "delete": "Delete",
    "deleteConfirm": "Delete this private entry?",
    "wrongPass": "Check your sign-in details.",
    "online": "Online",
    "offline": "Offline · connect to open the app",
    "ready": "Ready",
    "nowTitle": "For your shift",
    "myShift": "My shift",
    "nextLearning": "Next to learn",
    "allReference": "All reference",
    "myTasks": "My tasks",
    "shiftDutiesTitle": "Shift duties",
    "shiftDutiesNav": "Shift duties",
    "shiftDutyNightLabel": "Shift",
    "shiftArrival": "Arrive at work",
    "shiftDeparture": "Leave work",
    "shiftDutyAdd": "+ Add",
    "shiftDutyPlaceholder": "Task",
    "shiftDutyTimeOptional": "Optional time",
    "shiftDutyTonight": "Tonight only",
    "shiftDutyEmpty": "No extra duties",
    "shiftDutyEdit": "Edit duty",
    "shiftDutyDelete": "Delete duty",
    "shiftDutyDeleteConfirm": "Delete this duty?",
    "myProfile": "My profile",
    "fireQuick": "Fire & evacuation",
    "quickAction": "Quick Action",
    "peopleXDRecoveryAction": "PeopleXD sign-in problem",
    "mealAction": "Colleague meal",
    "mealRuleAction": "Record it at the till",
    "evacuationExit": "Use the nearest fire exit.",
    "evacuationAssembly": "Continue to the Assembly Point.",
    "add": "Add",
    "addTask": "One task…",
    "newShift": "Reset for a new shift",
    "findReference": "Search guidance…",
    "otherAccount": "Another account",
    "ownerAccount": "My existing account",
    "createAccount": "Create account",
    "recoverAccount": "Recover account",
    "accountName": "Username",
    "accountNameHint": "Use 3–40 letters, numbers, dots, underscores or hyphens.",
    "newPasswordHint": "Use at least 2 characters.",
    "accountUnavailable": "That username is unavailable.",
    "recoveryCode": "Recovery code",
    "keepRecovery": "Keep this code somewhere safe. You need it if you forget your password.",
    "done": "Done",
    "displayName": "Name",
    "manager": "Manager",
    "hours": "Weekly hours",
    "paidBreak": "Break",
    "annualHoliday": "Annual holiday (days)",
    "minibusNote": "Travel note",
    "shiftStart": "Shift starts",
    "shiftEnd": "Shift ends",
    "shiftDays": "Shift days",
    "hoursUnit": "hours",
    "addCourse": "Add course",
    "courseTitle": "Course title",
    "arabicTitleOptional": "Arabic title (optional)",
    "dueDate": "Due date",
    "progressLabel": "Progress",
    "notStarted": "Not started",
    "inProgress": "In progress",
    "optionalLearning": "Optional",
    "learningClear": "Required learning complete",
    "myProgress": "Pick a course and continue",
    "addFirstTask": "Add a task to start your checklist.",
    "deleteTaskConfirm": "Remove this task?",
    "deleteCourseConfirm": "Remove this course from your list?",
    "grossEstimate": "Weekly gross estimate",
    "firstDayTime": "Arrival time",
    "firstDayLocation": "Arrival location",
    "firstDayPostcode": "Postcode",
    "courseCount": "{n} courses",
    "myLearning": "My learning",
    "newIncident": "New incident",
    "mealsTab": "Meals",
    "discountsTab": "Discounts",
    "travelTab": "More",
    "leisureTab": "Leisure",
    "dailyTab": "At work",
    "foodTab": "Food handling",
    "issuedTab": "Your uniform",
    "resetTab": "Reset password",
    "usernameTab": "Username",
    "appTab": "App help",
    "shiftTab": "Shift & pay",
    "accountsTab": "Accounts",
    "arrivalTab": "First day",
    "privateDataError": "Your information is unavailable. Try again.",
    "sessionError": "Sign-in did not finish. Try again.",
    "mealSandwiches": "Only boxed/wrapped sandwiches are free. Other sandwiches, wraps, flatbreads, toasties and paninis: up to 75% off.",
    "adultMealRule": "The 75% meal discount applies to adult meals only.",
    "pendingTab": "To do",
    "retry": "Try again",
    "retryIntro": "Try opening your information again."
  }
};

Object.assign(TRANSLATIONS.en, {nextShift:'Next shift',setShift:'Your schedule',onShift:'On shift',workingToday:'Working today',dayOff:'Day off today',endsAt:'Finishes at {time}',setSchedule:'Choose your work days',signInShift:'Sign in to see your next shift',timeRemaining:'{time} left',startsIn:'Starts in {time}',durationDays:'d',durationHours:'h',durationMinutes:'min'});
Object.assign(TRANSLATIONS.ar, {nextShift:'الشيف الجاي',setShift:'مواعيد شغلك',onShift:'إنت في الشيف دلوقتي',workingToday:'عندك شيف النهارده',dayOff:'النهارده إجازة',endsAt:'بتخلص الساعة {time}',setSchedule:'اختار أيام شغلك',signInShift:'ادخل حسابك علشان تشوف الشيف الجاي',timeRemaining:'فاضل {time}',startsIn:'بيبدأ كمان {time}',durationDays:'يوم',durationHours:'ساعة',durationMinutes:'دقيقة'});
Object.assign(TRANSLATIONS.en,{homeBrowse:'Browse by topic',workGuides:'Benefits & guidance',mealGuide:'Colleague meals',discountGuide:'Discounts',minibusGuide:'Minibus',workTools:'Company apps & accounts',peopleXDHelp:'PeopleXD sign-in help',allReference:'Search all guidance'});
Object.assign(TRANSLATIONS.ar,{homeBrowse:'الأقسام والإرشادات',workGuides:'مزايا وإرشادات',mealGuide:'وجبات الموظفين',discountGuide:'الخصومات',minibusGuide:'الميني باص',workTools:'تطبيقات وحسابات الشركة',peopleXDHelp:'مساعدة دخول PeopleXD',allReference:'ابحث في كل الإرشادات'});
Object.assign(TRANSLATIONS.en,{workQuickHint:'Shifts, pay and account details',situationsTitle:'When something happens',alertsTitle:'Alerts',noAlerts:'Nothing needs your attention right now.',shiftAlertActive:'Your shift is underway',shiftAlertSoon:'Your next shift is coming up',nothingFound:'No matching guidance'});
Object.assign(TRANSLATIONS.ar,{workQuickHint:'الشيفت والأجر وبيانات الحساب',situationsTitle:'لو حصل موقف',alertsTitle:'التنبيهات',noAlerts:'مفيش حاجة محتاجة تنبيه دلوقتي.',shiftAlertActive:'إنت في الشيف دلوقتي',shiftAlertSoon:'شيفتك الجاية قربت',nothingFound:'مفيش إرشادات مطابقة'});

// Food-safety shift reference from WF-Training-Reference.md, §§19–59.
Object.assign(TRANSLATIONS.ar, {
  "foodGuideTitle": "سلامة الغذاء والحساسية",
  "foodGuideHint": "الحساسية · الحرارة · النظافة · الشكاوى",
  "foodAllergensTab": "طلبات الحساسية",
  "foodTempsTab": "الحرارة والتخزين",
  "foodHygieneTab": "النظافة والتلوث",
  "foodPestsTab": "الآفات والشكاوى",
  "foodLead": "لو مش متأكد من سلامة الطعام، ما تخمّنش وما تقدّموش على إنه آمن. اتبع إجراء الفرع.",
  "foodAllergyTitle": "عميل بيسأل عن حساسية؟",
  "foodAllergy1": "اسمع للعميل وحدد مسبّب الحساسية أو الحاجة الغذائية بالضبط.",
  "foodAllergy2": "استخدم Allergen Portal للصنف الفعلي؛ راجع Ingredients وAllergens وMay Contain.",
  "foodAllergy3": "افحص الصلصات والزيوت والزينة وتغييرات الوصفة أو المورد وخطر التلامس المتبادل.",
  "foodAllergy4": "بلّغ Service Leader واتبع إجراء الفرع؛ كل موظف يساعد العميل باستخدام البوابة.",
  "foodAllergy5": "لو المعلومات ناقصة أو الخطر غير محسوم، ما تضمنش إن المنتج خالٍ من مسبّب الحساسية.",
  "foodEmergencyTitle": "حساسية مفرطة؟ اتصل بـ999",
  "foodEmergencyDesc": "صعوبة التنفس أو تورّم اللسان/الحلق أو دوخة شديدة أو انهيار قد تعني حالة طارئة، حتى بدون طفح. اتبع تعليمات الإسعاف.",
  "foodFirstAid": "إرشادات الإسعافات الأولية",
  "foodGfTitle": "Gluten Free ولا Made without Gluten؟",
  "foodGfDesc": "طبقًا لوثيقة الشركة: Gluten Free للمنتجات المعبأة من مورد وعليها وسم صريح؛ Made without Gluten يعني عدم إضافة غلوتين للوصفة مع احتمال التلامس في بيئة مشتركة، وتعتبره السياسة غير مناسب للسيلياك. اختبار آخر يستخدم GF بصورة متعارضة؛ اسأل Service Leader وراجع الملصق الفعلي.",
  "foodAllergenListTitle": "الفئات الـ14 لمسببات الحساسية",
  "foodAllergenList": "الكرفس؛ الحبوب المحتوية على الغلوتين؛ القشريات؛ البيض؛ السمك؛ الترمس؛ الحليب؛ الرخويات؛ الخردل؛ الفول السوداني؛ السمسم؛ فول الصويا؛ ثاني أكسيد الكبريت والكبريتيت؛ المكسرات الشجرية. ممكن توجد حساسية خارج هذه القائمة.",
  "foodPPDSTitle": "Natasha’s Law: ملصقات PPDS",
  "foodPPDSDesc": "لو الطعام اتعبّى قبل اختيار العميل لبيعه مباشرة في نفس الموقع، لازم تراجع اسم الطعام وقائمة المكونات كاملة وإبراز مسببات الحساسية على العبوة. عند غياب ملصق صحيح أو تغير الوصفة، صعّد قبل البيع. لا تعمم غرامة £5,000 الظاهرة بالفيديو.",
  "foodAllergyNotice": "المصدر: مرجع التدريب §§19–21 و56–59. مفيش رابط دخول معتمد للبوابة في المرجع؛ استخدم وسيلة الوصول الرسمية في موقعك.",
  "foodTempNotice": "دي أرقام مذكورة في تدريب الشركة. اتبع حدود وسجلات الموقع الحالية؛ التصعيد أفضل من التخمين عند وجود اختلاف.",
  "foodCook": "طهي / إعادة تسخين",
  "foodCookDetail": "75°C أو أعلى",
  "foodHolding": "حفظ ساخن",
  "foodHoldingDetail": "63°C أو أعلى",
  "foodChilling": "هدف الثلاجة",
  "foodChillingDetail": "≤5°C، والتصرف عند تجاوز 8°C",
  "foodFreezing": "فريزر / مجمّد",
  "foodFreezingDetail": "−18°C أو أبرد حسب ورقة التخزين",
  "foodCheckTitle": "أثناء الاستلام والتجهيز",
  "foodCheck1": "افحص حرارة الشحنة وسلامة العبوة، وارفض غير المناسب، وانقل المبرد/المجمد إلى مكانه فورًا.",
  "foodCheck2": "استخدم مسبار حرارة نظيفًا ومطهّرًا وسجّل وفق CHECK65 وتعليمات الموقع.",
  "foodCheck3": "افصل النيئ عن الجاهز للأكل، وخزن اللحوم النيئة تحته لمنع تسرب السوائل.",
  "foodFifoTitle": "FIFO: الأقدم يطلع الأول",
  "foodFifoDesc": "قدّم الأقدم والأقرب إلى Use By في الاستخدام. Use By تاريخ سلامة، وBest Before تاريخ جودة. ما تستخدمش طعامًا بعد Use By.",
  "foodCoolingTitle": "التبريد والسجلات — انتبه لاختلاف المصادر",
  "foodCoolingDesc": "برّد الطعام بسرعة بحصص صغيرة مع سجل التبريد. ورقتان تختلفان في معنى 90 دقيقة، ووتيرة فحص الثلاجات 4 مرات في واحدة و5 في الأخرى. وثيقة نقل تجميد تحتوي قيمة +25°C خاطئة. اطلب أحدث تعليمات الموقع بدل اعتماد صياغة ملتبسة.",
  "foodHygieneLead": "المكان ممكن يبان نظيف وهو مش صحي. النظافة الظاهرية غير التعقيم السليم.",
  "foodSickTitle": "القيء أو الإسهال: 48 ساعة",
  "foodSickDesc": "بلّغ المدير. ما ترجعش لتداول الطعام قبل مرور 48 ساعة كاملة من انتهاء آخر عرض، واتبع تعليمات العودة.",
  "foodHandsTitle": "غسل اليدين والقفازات",
  "foodHandsDesc": "اغسل إيدك قبل تداول الطعام وبعد الحمام والنيئ والقمامة والعطس ولمس الوجه وبين المهام. القفازات لا تغني عن غسل اليدين.",
  "foodCrossTitle": "امنع التلوث المتبادل",
  "foodCrossDesc": "افصل مكونات الحساسية والطعام النيئ والجاهز؛ استخدم أدوات ومساحات منفصلة أو منظفة ومطهّرة، واغسل اليدين. سكينة مشتركة ممكن تنقل الغلوتين.",
  "foodClothingTitle": "الزي والجروح",
  "foodClothingDesc": "الملابس نظيفة والشعر مربوط في التحضير؛ غطِّ الجروح بضمادة زرقاء مقاومة للماء وأبلغ المدير. التزم بقواعد المجوهرات والأظافر حسب طبيعة المهمة.",
  "foodCleanerTitle": "المنظفات والمطهرات",
  "foodCleanerDesc": "اتبع ملصق المنتج وتعليمات تركيزه ووقت ملامسته للأسطح، وابعده عن الغذاء. رقم D10 الوارد في سؤال ليس تعليمات لكل عبوة.",
  "foodReportLead": "أمّن الطعام والأشخاص، وأبلغ المدير/قائد الخدمة فورًا؛ ما تعالجش مشكلة أكبر من تدريبك.",
  "foodPestTitle": "فأر أو فضلات آفات؟",
  "foodPestDesc": "بلّغ فورًا، احمِ الطعام وتخلّص من المشتبه بتلوثه حسب تعليمات الموقع، واترك المكافحة للمختص. EFK اختصار Electric Fly Killer.",
  "foodComplaintTitle": "شكوى تسمم أو حساسية أو جسم غريب",
  "foodComplaintDesc": "أبلغ قائد الخدمة واجمع الوقائع والأدلة دون تخمين. عرض التدريب: Alert65 ← Food Complaints ← Log a food complaint، مع اختيار الفرع والنوع وإدخال التفاصيل ثم Submit. الفيديو لا يثبت شكل النظام الحالي.",
  "foodLastNote": "هذه خلاصة للعمل السريع من وثائق Westmorland؛ عند تعارض رقم أو سياسة أو اختلاف نوع المنتج ارجع لأحدث تعليمات الفرع.",
  "foodCardTitle": "اعتماد بطاقة Welcome Antlers",
  "foodCardDesc": "بعد شرح البنود للمدرب وتأكيده، اكتب اسمه الحقيقي وتاريخ إكمال البطاقة في THRIVE، وأرفق مستندًا فقط إن طُلب، واضغط Confirm. يلزم بعدها اعتماد Line Manager. لا تعتبر الفيديو أو Confirm إثبات إكمال."
});
Object.assign(TRANSLATIONS.en, {
  "foodGuideTitle": "Food safety & allergens",
  "foodGuideHint": "Allergens · temperatures · hygiene · complaints",
  "foodAllergensTab": "Allergy requests",
  "foodTempsTab": "Temperatures & storage",
  "foodHygieneTab": "Hygiene & cross-contact",
  "foodPestsTab": "Pests & complaints",
  "foodLead": "If you cannot confirm food safety, never guess or claim the product is safe. Follow the site procedure.",
  "foodAllergyTitle": "A customer asks about an allergy?",
  "foodAllergy1": "Listen and identify the customer's exact allergen or dietary requirement.",
  "foodAllergy2": "Use Allergen Portal for the exact product; check Ingredients, Allergens and May Contain.",
  "foodAllergy3": "Check sauces, oils, toppings, recipe/supplier changes and cross-contact.",
  "foodAllergy4": "Notify the Service Leader and follow site policy; all colleagues help customers using the portal.",
  "foodAllergy5": "If information is missing or risks cannot be resolved, never guarantee allergen-free food.",
  "foodEmergencyTitle": "Anaphylaxis? Call 999",
  "foodEmergencyDesc": "Breathing difficulty, tongue/throat swelling, severe dizziness or collapse can mean an emergency, even without a rash. Follow ambulance instructions.",
  "foodFirstAid": "First aid guidance",
  "foodGfTitle": "Gluten Free or Made without Gluten?",
  "foodGfDesc": "Company guidance: Gluten Free refers to supplier-prepacked, labelled products; Made without Gluten excludes gluten ingredients but can share preparation areas and is not suitable for coeliacs under the documented policy. Another quiz uses conflicting GF wording; check the actual label and Service Leader.",
  "foodAllergenListTitle": "The 14 regulated allergen groups",
  "foodAllergenList": "Celery; cereals containing gluten; crustaceans; eggs; fish; lupin; milk; molluscs; mustard; peanuts; sesame; soybeans; sulphur dioxide and sulphites; tree nuts. Other foods can also cause allergies.",
  "foodPPDSTitle": "Natasha’s Law: PPDS labelling",
  "foodPPDSDesc": "For food packed before selection for direct sale at the premises, check the food name, full ingredients and emphasised allergens on pack. Escalate missing/outdated labels before sale. The video's £5,000 figure is not a universal legal penalty.",
  "foodAllergyNotice": "Source: training §§19–21 and 56–59. No verified portal login URL is documented; use your site's official access route.",
  "foodTempNotice": "These values come from company training; follow current site limits and records and escalate uncertain readings.",
  "foodCook": "Cook / reheat",
  "foodCookDetail": "75°C or higher",
  "foodHolding": "Hot holding",
  "foodHoldingDetail": "63°C or above",
  "foodChilling": "Fridge target",
  "foodChillingDetail": "≤5°C; act if above 8°C",
  "foodFreezing": "Freezer / frozen",
  "foodFreezingDetail": "−18°C or colder per storage sheet",
  "foodCheckTitle": "At delivery and preparation",
  "foodCheck1": "Check delivery temperature and packaging; reject unsuitable goods and put cold stock away promptly.",
  "foodCheck2": "Use a cleaned and disinfected probe; record according to CHECK65 and the site procedure.",
  "foodCheck3": "Separate raw from ready-to-eat foods and keep raw meat below them to avoid dripping.",
  "foodFifoTitle": "FIFO: First In, First Out",
  "foodFifoDesc": "Use older goods and the earliest Use By first. Use By concerns safety; Best Before concerns quality. Do not use food after Use By.",
  "foodCoolingTitle": "Cooling and logs — sources disagree",
  "foodCoolingDesc": "Cool food quickly in small portions and keep cooling records. Two sheets differ over the 90-minute requirement and specify four versus five daily fridge checks. A transport sheet has an erroneous +25°C frozen-food value. Confirm current site policy.",
  "foodHygieneLead": "A workplace can look clean without being hygienic. Follow approved cleaning and disinfection.",
  "foodSickTitle": "Vomiting or diarrhoea: 48 hours",
  "foodSickDesc": "Tell your manager. Do not handle food until 48 full hours after symptoms end; follow return-to-work instructions.",
  "foodHandsTitle": "Handwashing and gloves",
  "foodHandsDesc": "Wash hands before handling food and after toilets, raw foods, waste, sneezing, touching your face and between tasks. Gloves do not replace handwashing.",
  "foodCrossTitle": "Prevent cross-contact",
  "foodCrossDesc": "Separate allergen-controlled, raw and ready-to-eat foods. Use separate or thoroughly cleaned equipment and wash hands. A shared knife can transfer gluten.",
  "foodClothingTitle": "Clothing and cuts",
  "foodClothingDesc": "Wear clean clothes, restrain hair in food preparation and cover cuts with a blue waterproof dressing; tell your manager. Follow task-specific jewellery and nail rules.",
  "foodCleanerTitle": "Cleaning chemicals",
  "foodCleanerDesc": "Follow the actual product label for dilution and contact time; keep chemicals away from food. A D10 quiz answer does not apply to every container.",
  "foodReportLead": "Protect people and food; tell the manager/Service Leader promptly. Do not attempt unsafe or unauthorised actions.",
  "foodPestTitle": "Mouse or pest signs?",
  "foodPestDesc": "Report immediately, protect food and dispose of potentially contaminated items under site instructions. Leave pest control to specialists. EFK means Electric Fly Killer.",
  "foodComplaintTitle": "Suspected poisoning, allergy or foreign-body complaint",
  "foodComplaintDesc": "Tell the Service Leader and capture facts and evidence without guessing. Training route: Alert65 → Food Complaints → Log a food complaint; select site/type, record details and Submit. The training video does not confirm today's interface.",
  "foodLastNote": "Concise Westmorland training reference; where a value, policy or product classification differs, follow current site guidance.",
  "foodCardTitle": "Welcome Antlers training-card sign-off",
  "foodCardDesc": "After the trainer explains and signs off all points, enter their real name and the completion date in THRIVE, attach a file only if required, and press Confirm. Line Manager approval is still needed. A video or Confirm alone is not proof of completion."
});


// Verified quick-use guidance from WF-Training-Reference §§62–63 (10 Oct 2026).
Object.assign(TRANSLATIONS.ar, {
  "fcTab": "محطة الوقود",
  "fcFireNote": "في حريق محطة الوقود: أوقف المضخات بزر الطوارئ إذا كان آمنًا، واطلب الإطفاء على 999 حتى لو اتصل الإنذار تلقائيًا. أخلِ الساحة، وساعد الآخرين دون دخول منطقة خطرة.",
  "fcUrgentLabel": "تصرف فوري — تسرب وقود",
  "fcEmergencyTitle": "تسرب وقود في الساحة",
  "fcEmergencyHint": "أوقف الضخ واحمِ الناس أولًا؛ لا تتدخل في تسرب غير آمن أو أكبر من قدرتك وتدريبك.",
  "fcSpillStop": "أوقف المضخة المتأثرة والمضخات القريبة. لو التسرب كبير (أكثر من 5 لترات) أو فيه خطر، استخدم إيقاف الطوارئ لجميع المضخات.",
  "fcSpillProtect": "أبعد العملاء عن المنطقة، واعزلها بأقماع أو شريط إن كان آمنًا. لا تشغّل محركات بالقرب من الوقود؛ لا تقترب من الأبخرة.",
  "fcSpillCall": "أكثر من 5 لترات، أو تسرب لا يمكنك السيطرة عليه بأمان؟ أغلق الساحة، اتصل بـ999 واطلب الإطفاء، وأبلغ Duty Manager.",
  "fcSpillReturn": "لا تعِد فتح الساحة بعد حادث كبير إلا بعد سماح خدمات الطوارئ. سجّل كل التسربات مهما كان حجمها. التعامل بالرمل الجاف ومعدات الحماية للمدرَّبين إذا كان آمنًا.",
  "fcSpillWarning": "ملاحظة من مرجع الشركة: هناك تداخل بين وصف تسرب صغير «أقل من 3 لترات» وكبير «1–5 لترات». لا تخمّن الفئة؛ ارجع لمسؤول الموقع وتصرف حسب الخطر.",
  "fcEverydayTitle": "مرجع الشفت — افتح ما تحتاجه",
  "fcPumpTitle": "قبل السماح بتعبئة الوقود",
  "fcPump1": "لا تشغّل أي مضخة إلا مع رؤية واضحة للعميل والمضخات طوال التشغيل؛ لا تترك التيل أثناء الضخ إلا للطوارئ.",
  "fcPump2": "تأكد من إطفاء محرك السيارة، وأن من يعبئ الوقود عمره 16 سنة على الأقل، وأن الفوهة داخل فتحة التعبئة جيدًا.",
  "fcPump3": "سياسة الشركة تمنع التدخين/الفيب واستخدام الموبايل في منطقة المضخات. أوقف الضخ واطلب وقف السلوك عبر نظام النداء قبل إعادة السماح.",
  "fcNightTitle": "الوردية الليلية — Night Hatch",
  "fcNightBody": "في أوقات الخطورة التي يحددها تقييم أمن الموقع: لا تفتح باب المتجر إلا إذا كان أكثر من موظف موجودًا وعلى رأس العمل. لو وحدك، استخدم Night Hatch فقط وأغلق باب المتجر بإحكام. تأكد من أوقات ومكان التطبيق مع مديرك.",
  "fcDeliveryTitle": "استلام صهريج الوقود",
  "fcDelivery1": "قبل وبعد التسليم: اطبع فحص الماء من TANK GAUGE، وليس التيل. لو ظهر ماء قبل التسليم لا يُسلَّم الوقود للخزان المصاب.",
  "fcDelivery2": "لو ظهر ماء بعد التسليم، أبقِ مضخات الخزان المتأثر خارج الخدمة. افحص قراءة الجهاز بعد 30 دقيقة واتبع تعليمات FM/GFM دون إعادة تشغيل من نفسك.",
  "fcDelivery3": "احتفظ بنسخ أوراق التسليم وقراءات ما قبل/بعد ومفاتيح الخزان/VR. لا تُنجز أوراق التسليم أو تُترك وحدك أثناءه دون تدريب PRA والتفويض المطلوب.",
  "fcDeliveryConflict": "يوجد اختلاف بين بند 8 في نسختين من سياسة التسليم، منها إعادة فحص بعد 30 دقيقة إضافية في النسخة الأقدم. اتبع نسخة الفرع المعتمدة ومديرك.",
  "fcPaymentTitle": "مشكلات العملاء والدفع",
  "fcPayment1": "Drive Off / No Means of Payment: بلّغ باستخدام جهاز ForeCourt Eye وفق تدريب المدير والفيديو الموجود عليه. لا تطارد المركبات أو تعترضها.",
  "fcPayment2": "وقود خطأ في سيارة العميل: أخبره ألا يشغّل المحرك، ويطلب Recovery Service؛ وإذا لزم نقل السيارة تُدفع إلى مكان آمن. يبقى ثمن الوقود مستحقًا حسب سياسة الشركة.",
  "fcPayment3": "Pump crossover: أكد رقم المضخة والمبلغ قبل التحصيل. لو حصل خطأ، اطلب مساعدة Team Leader؛ الاسترداد/الفرق ونموذج Pump Cross Over يتمان بالطريقة المصرح بها فقط.",
  "fcContainerTitle": "تعبئة جراكن الوقود",
  "fcContainerBody": "اسمح فقط بوعاء مُعلّم أنه مناسب للبنزين/الديزل، خارج السيارة وعلى أرض الساحة، مع تشغيل يدوي للفوهة وإغلاق الغطاء فورًا. يوجد اختلاف في حد العبوة المعدنية بين نسختين من المرجع (9 و25 لترًا)؛ تأكد من سياسة الفرع قبل التصريح.",
  "fcSource": "المصدر: Westmorland Forecourt Policies & Procedures (مايو 2026 وبعض صفحات أقدم) — مرجع التدريب §62. تفاصيل الموقع وصلاحياتك يحددها التدريب الميداني والمدير.",
  "fcReportLink": "إجراءات الإبلاغ عن الحوادث ↗",
  "speakTab": "الإبلاغ والحماية",
  "speakTitle": "تحرش جنسي أو سلوك غير مرغوب؟",
  "speakIntro": "يشمل السلوك الجنسي غير المرغوب كلامًا، لمسًا، رسائل أو تصرفات من زميل أو عميل. تقدر تطلب الدعم أو تبلّغ حتى لو كنت شاهدًا.",
  "speakContactNote": "People Team — جهة تواصل مؤكدة في سياسة Westmorland. يمكنك أيضًا التحدث إلى مديرك أو مدير آخر.",
  "speakHowTitle": "كيف تتصرف؟",
  "speakHow1": "لو آمن ومريح لك، تقدر تطلب من الشخص يتوقف. مش مطلوب منك مواجهته قبل الشكوى.",
  "speakHow2": "بلّغ Line Manager أو مديرًا مناسبًا آخر أو People Team. اختر الشخص اللي ترتاح له؛ يمكن البدء بطلب الدعم والمشورة.",
  "speakHow3": "سجّل الوقائع والتواريخ والمكان والشهود والرسائل المتعلقة بالموقف إن كانت متاحة وآمنة. لا تتداول محتوى جنسيًا أو صورًا محرجة بلا ضرورة.",
  "speakExamplesTitle": "أمثلة وإرشادات",
  "speakExamples": "نكات وإيحاءات جنسية، لمس غير مرغوب، أسئلة شخصية ملحّة، نظرات أو رموز ذات دلالة جنسية، ورسائل في جروبات العمل حتى لو كانت عن شخص غير موجود. المناسبات المرتبطة بالعمل وتعاملات العملاء مش استثناءً.",
  "speakRightsTitle": "المساندة والخصوصية",
  "speakRights": "تمنع سياسة الشركة الانتقام بسبب الإبلاغ أو مساندة شخص آخر (victimisation). تُعامل الشكاوى بحساسية وسرية حسب الحاجة للتحقيق، لكن لا يوجد ضمان مُثبت ببلاغ مجهول الهوية. قد يكون المسار رسميًا أو لدعم الموظف أولًا.",
  "speakSource": "المصدر: Westmorland Prevention of Sexual Harassment Policy (مراجعة 22/11/2024) وReporting Sexual Harassment — مرجع التدريب §63. عند تهديد فوري اتبع إجراءات السلامة والطوارئ.",
  "verifiedQuizTitle": "اختبار منع التحرش الجنسي — نتيجة موثقة",
  "verifiedQuizNote": "من صور THRIVE: نجحت من أول محاولة. هذه ملاحظة مرجعية وليست تحديثًا تلقائيًا لقائمة تدريب حسابك. بطاقة Welcome Antlers تحتاج اعتمادًا عمليًا."
});
Object.assign(TRANSLATIONS.en, {
  "fcTab": "Forecourt",
  "fcFireNote": "Forecourt fire: stop pumps using the emergency shut-off if safe; call 999 even if the alarm auto-dials the fire service. Evacuate the forecourt; do not enter unsafe areas to complete checks.",
  "fcUrgentLabel": "IMMEDIATE ACTION — FUEL SPILL",
  "fcEmergencyTitle": "Fuel spill on the forecourt",
  "fcEmergencyHint": "Stop dispensing and protect people first. Do not tackle a spill beyond your training or safety.",
  "fcSpillStop": "Stop the pump in use and nearby pumps. For a major spill (over 5 litres), or immediate danger, use the emergency shut-off for all pumps.",
  "fcSpillProtect": "Move customers away; cordon off the area with cones or tape if safe. Do not start engines near fuel or enter areas with hazardous vapour.",
  "fcSpillCall": "Over 5 litres, or too large to manage safely? Close the forecourt, dial 999 and ask for Fire Service; inform the Duty Manager.",
  "fcSpillReturn": "Reopen after a major spill only when emergency services say it is safe. Record every spill, however small. Only trained staff should use dry sand/PPE when safe.",
  "fcSpillWarning": "Company source conflict: 'small' is described as under 3 litres, but 'large' as 1–5 litres. The ranges overlap; do not guess. Escalate and assess the actual hazard.",
  "fcEverydayTitle": "On-shift reference — open as needed",
  "fcPumpTitle": "Before authorising a pump",
  "fcPump1": "Keep uninterrupted sight of the customer and pumps while dispensing. Do not leave the till during dispensing except in an emergency.",
  "fcPump2": "Engine off, person dispensing appears aged 16 or older, and nozzle properly inserted in the vehicle filler.",
  "fcPump3": "Company policy prohibits smoking/vaping and mobile phone use in the pump area. Stop dispensing and ask them to stop using the tannoy before reauthorising.",
  "fcNightTitle": "Night shift — hatch-only rule",
  "fcNightBody": "During site-assessed vulnerable hours, the shop door is opened only when more than one colleague is on duty and present. If working alone, trade through the Night Hatch only and secure the shop door. Check your site's exact hours and layout.",
  "fcDeliveryTitle": "Accepting a fuel tanker delivery",
  "fcDelivery1": "Before and after delivery, use water-check printouts from the TANK GAUGE (not the till). If water is present before delivery, do not accept fuel into that tank.",
  "fcDelivery2": "If water shows after delivery, keep pumps supplied by that tank out of service. Recheck the gauge after 30 minutes and follow FM/GFM instructions; do not personally reopen them.",
  "fcDelivery3": "Keep the site/driver delivery notes, before/after gauge printouts and tank/VR keys. Do not complete delivery paperwork or be left alone during delivery without the required PRA training and authorisation.",
  "fcDeliveryConflict": "Step 8 differs between versions: an older copy mentions another 30-minute check. Follow your current site-approved procedure and manager.",
  "fcPaymentTitle": "Customer and payment exceptions",
  "fcPayment1": "Drive Off / No Means of Payment: use the ForeCourt Eye tablet as trained by your manager and its tutorial. Never chase or intercept a vehicle.",
  "fcPayment2": "Wrong fuel: tell the driver NOT to start the engine; contact recovery. Push the vehicle to safety if it must be moved. Company policy says fuel is still payable.",
  "fcPayment3": "Pump crossover: confirm pump number and amount before charging. If charged incorrectly, get the Team Leader; refunds/differences and the Pump Cross Over form follow your authorised training.",
  "fcContainerTitle": "Approved fuel containers",
  "fcContainerBody": "Use only a marked petrol/diesel-suitable container, placed on the forecourt (not in a car). Hold the nozzle lever manually and secure the cap promptly. Company copies conflict on the metal-container limit (9 vs 25 litres); confirm your site's policy before authorising.",
  "fcSource": "Source: Westmorland Forecourt Policies & Procedures (May 2026 and earlier pages), training reference §62. Site layout, training and authorisations take precedence.",
  "fcReportLink": "Incident reporting procedure ↗",
  "speakTab": "Speak up & support",
  "speakTitle": "Sexual harassment or unwanted conduct?",
  "speakIntro": "Unwanted sexual behaviour can involve words, touching, messages or conduct by a colleague or customer. You can seek support or report what you witness.",
  "speakContactNote": "People Team — confirmed contact from Westmorland policy. You can also speak to your Line Manager or another manager.",
  "speakHowTitle": "What to do",
  "speakHow1": "If you feel safe and comfortable, you may ask the person to stop. Confronting them is not a precondition for reporting.",
  "speakHow2": "Tell your Line Manager, another appropriate manager or the People Team. You may first ask for advice and support.",
  "speakHow3": "Note what happened, dates, location, witnesses and relevant messages where available and safe. Avoid forwarding sexual content or humiliating images unnecessarily.",
  "speakExamplesTitle": "Examples & boundaries",
  "speakExamples": "Sexual jokes or innuendo, unwanted touching, intrusive questions, sexual gestures or emojis, and work-group messages—even about an absent colleague. Work-linked events and customer conduct count too.",
  "speakRightsTitle": "Support, confidentiality and victimisation",
  "speakRights": "The company prohibits adverse treatment for raising or supporting a complaint (victimisation). Reports are treated sensitively and as confidentially as the process permits, but anonymity is not guaranteed. Reporting may begin with support or lead to a formal process.",
  "speakSource": "Source: Westmorland Prevention of Sexual Harassment Policy (reviewed 22/11/2024) and Reporting Sexual Harassment, reference §63. For immediate threats, follow emergency safety procedures.",
  "verifiedQuizTitle": "Sexual harassment prevention quiz — verified result",
  "verifiedQuizNote": "From THRIVE screenshots: passed on first attempt. This is a reference note, not an automatic change to your private training list. Welcome Antlers still requires practical sign-off."
});
