export const TRANSLATIONS = {
  "ar": {
    "back": "رجوع",
    "returnCompanion": "الرجوع لمساعد الموظف",
    "logout": "تسجيل الخروج",
    "apiError": "مش قادر أفتح بياناتك دلوقتي. حاول تاني.",
    "tooMany": "محاولات كتير. حاول بعد شوية.",
    "conflict": "البيانات اتغيّرت على جهاز تاني. افتح القسم تاني وحاول الحفظ.",
    "edit": "تعديل",
    "editAccountDetails": "تعديل بيانات الحسابات",
    "workPin": "الرقم السري للشغل",
    "thriveUsername": "اسم المستخدم في THRIVE",
    "importOldVault": "استيراد الخزنة القديمة",
    "importOldIntro": "اكتب كلمة مرور الخزنة القديمة على الجهاز ده لاستيراد محتوياتها. النسخة القديمة هتفضل محفوظة.",
    "oldPassword": "كلمة المرور القديمة",
    "importEntries": "استيراد",
    "importDone": "تم استيراد المحتويات وحفظها.",
    "emptyOldVault": "الخزنة القديمة مفيهاش محتويات.",
    "importFailed": "تعذر فتح الخزنة القديمة. راجع كلمة المرور.",
    "logoutFailed": "تم قفل البيانات هنا. تعذر إكمال تسجيل الخروج؛ حاول تاني.",
    "saveFailed": "تعذر الحفظ. محتوياتك لسه مفتوحة؛ حاول تاني.",
    "invalidEntry": "راجع حجم البيانات المدخلة.",
    "appTitle": "مساعد موظف ويستمورلاند",
    "enterPass": "اكتب كلمة المرور علشان تفتح بياناتك الشخصية.",
    "passphrase": "كلمة المرور",
    "unlock": "فتح",
    "lock": "قفل",
    "fastReference": "مساعد الموظف",
    "findSeconds": "شفتك قدامك.",
    "confirmedOnly": "نفّذ. علّم. لاقي.",
    "emergency": "طوارئ",
    "fire": "حريق",
    "reference": "المرجع",
    "workDetails": "بيانات الشغل",
    "training": "التدريب",
    "accountHelp": "مساعدة الدخول",
    "benefits": "المزايا",
    "uniformDress": "الزي والمظهر",
    "privateVault": "الخزنة الخاصة",
    "backHome": "→ الرئيسية",
    "fireHeadline": "إنذار الحريق ← أقرب مخرج حريق ← نقطة التجمع",
    "fireIntro": "اخرج من أقرب مخرج حريق. كمّل لنقطة التجمع.",
    "forecourtSafe": "محطة الوقود — لو آمن تعمل كده",
    "fireStep1": "راجع أرضية محل محطة الوقود.",
    "fireStep2": "راجع المخزن.",
    "fireStep3": "راجع الحمامات.",
    "fireStep4": "الموظف المكلّف ياخد جدول العاملين معاه لنقطة التجمع.",
    "onlyIfSafe": "لو ده آمن فقط.",
    "wardenTitle": "مسؤول الحريق — بس لو الدور ده متكلف بيه",
    "warden1": "افحص مكان الحريق لو ده آمن.",
    "warden2": "فعّل أقرب نقطة إنذار يدوية لو لسه ما اتفعّلتش.",
    "warden3": "تعامل بس مع حريق في بدايته، لو آمن وداخل حدود التدريب اللي أخدته من الشركة.",
    "warden4": "ساعد في الإخلاء واتواصل مع المديرين والمشرفين عند نقطة التجمع.",
    "warden5": "امنع أي حد يرجع يدخل المبنى لحد ما خدمة الإطفاء تقول إنه آمن.",
    "warden6": "بلّغ خدمة الإطفاء بمكان وطبيعة الحريق، وأي شخص مش متأكدين من وجوده، وأي مخاطر.",
    "myJob": "شغلي",
    "role": "الوظيفة",
    "roleValue": "عضو فريق – محطة الوقود (ليل)",
    "site": "الموقع",
    "lineManager": "المدير المباشر",
    "managerEmail": "إيميل المدير",
    "colleagueNumber": "رقم الموظف",
    "startDate": "تاريخ البداية",
    "shiftPay": "الشفت والمرتب",
    "regularShifts": "الشفتات الثابتة",
    "regularShiftsValue": "الجمعة والسبت",
    "shiftTime": "ميعاد الشفت",
    "contractedHours": "الساعات المتعاقد عليها",
    "hourlyRate": "الأجر بالساعة",
    "payFrequency": "الدفع",
    "weekly": "أسبوعي",
    "breakLabel": "البريك",
    "breakValue": "مدفوع",
    "payrollTiming": "مواعيد السنة والدفع",
    "companyYear": "السنة",
    "companyYearValue": "1 أبريل – 31 مارس",
    "payWeekEnds": "نهاية أسبوع الدفع",
    "payWeekEndsValue": "الأحد",
    "payDay": "يوم الدفع",
    "payDayValue": "الجمعة اللي بعده — دفع أسبوعي",
    "kioskSettings": "إعدادات الكشك",
    "kioskId": "رقم الكشك",
    "kioskPin": "الرقم السري",
    "temporaryId": "رقم مؤقت",
    "companyId": "معرّف الشركة",
    "username": "اسم المستخدم",
    "workspace": "مساحة العمل",
    "openPeopleXD": "افتح تطبيق PeopleXD",
    "openThrive": "افتح تطبيق THRIVE",
    "firstDay": "أول يوم / التعريف بالشركة",
    "date": "التاريخ",
    "time": "الوقت",
    "location": "المكان",
    "inductionLocation": "Westmorland Hotel — الاتجاه الشمالي",
    "postcode": "الرمز البريدي",
    "privateCodes": "الأكواد الخاصة",
    "privateCodesNote": "أرقامك وبيانات حساباتك.",
    "openVault": "افتح الخزنة الخاصة",
    "onlineTraining": "التدريب أونلاين",
    "requiredTraining": "التدريبات المطلوبة",
    "essentialLearning": "الأساسي — أولوية حالية",
    "otherAssignedTraining": "تدريبات مطلوبة أخرى",
    "completedLearning": "التدريبات اللي تمت",
    "completed": "تم",
    "course1": "تعريف الزملاء الجدد",
    "course2": "سلامة الغذاء",
    "course3": "الصحة والسلامة",
    "course4": "مراجعة الوعي بالحساسية",
    "completed1": "إجراء وجبات الموظفين",
    "completed2": "الكيك الموسمي الجديد من مطبخ Westmorland – Tebay",
    "completed3": "طريقة استخدام صفحة التعلّم",
    "completed4": "طريقة إضافة المحتوى",
    "completed5": "طريقة استخدام الصفحة الرئيسية والاستكشاف",
    "completed6": "منصة My Westmorland Learn",
    "completed7": "كتيّب مدرسة الطبخ",
    "completed8": "كتيّب المسار الوظيفي",
    "completed9": "خريطة طريق تطوير العمليات",
    "completed10": "قيم عائلة Westmorland",
    "completed11": "قصة Antlers",
    "completed12": "مواقعنا",
    "completed13": "Welcome Antlers – نظرة عامة للموظف",
    "completed14": "حزمة إطلاق «الأكل الجاهز والسلطات» – أكتوبر 2026",
    "course5": "تجربة العميل – طريقة Westmorland",
    "course6": "إجراءات CBE – موظفي محطة الوقود",
    "course7": "منع التحرش الجنسي",
    "peopleAccessTitle": "دخول PeopleXD",
    "usernameRule": "اسم المستخدم",
    "usernameRuleValue": "هو رقم الموظف — 6 أرقام وبيبدأ بـ 0",
    "usernameUnknown": "لو مش فاكره",
    "usernameUnknownValue": "اسأل مديرك المباشر أو ابعت لـ help@mywestmorland.com باسمك الكامل",
    "forgotPassword": "نسيت الباسورد",
    "resetStep1": "افتح mywestmorland.com.",
    "resetStep2": "My Westmorland People ← Forgot Password.",
    "resetStep3": "رقم الموظف + تاريخ الميلاد ← Reset Password.",
    "resetStep4": "افتح إيميل الاسترجاع، أكّد بياناتك وحدد كلمة مرور جديدة.",
    "openResetSite": "افتح صفحة استرجاع PeopleXD",
    "bothForgotten": "نسيت الباسورد وأسئلة الأمان؟",
    "bothForgottenValue": "ابعت لـ help@mywestmorland.com باسمك الكامل. فريق شؤون الموظفين هيعمل إعادة تعيين يدوي.",
    "emailPeopleTeam": "راسل فريق شؤون الموظفين",
    "passwordRules": "شروط الباسورد",
    "passwordRulesValue": "١٢ حرف أو أكتر: حرف كبير، حرف صغير، رقم ورمز.",
    "appFallback": "لو التطبيق مش شغال",
    "appFallbackValue": "استخدم mywestmorland.com للدخول على PeopleXD وحجز الإجازات. لو احتجت، جرّب جهاز محدّث أو لابتوب أو تابلت.",
    "openBrowserPortal": "افتح PeopleXD في المتصفح",
    "uniformTitle": "الزي والملابس",
    "uniformProvided": "الشركة بتوفر",
    "uniformProvidedValue": "معظم الزي المطلوب مجانًا — عادةً تيشيرت أو قميص، مريلة، جاكيت فليس أو بلوفر",
    "ownItems": "عليك أنت عادةً",
    "ownItemsValue": "البنطلون والحذاء، إلا لو حذاء الأمان جزء من معدات الوقاية الشخصية",
    "replacement": "الاستبدال",
    "replacementValue": "مجاني مع الاستهلاك الطبيعي؛ ممكن يتم التحصيل لو التلف أو الاستبدال خارج المعقول",
    "outsideWork": "الشغل بره",
    "outsideWorkValue": "ملابس دافئة ومقاومة للمطر متاحة؛ وفي الصيف ممكن قبعة وواقي شمس",
    "ppeTitle": "معدات الوقاية الشخصية (PPE)",
    "ppeValue": "لو اتسلمت حذاء أمان أو ملابس عالية الوضوح أو أي معدات وقاية شخصية، لازم تلبسها وقت الشغل المطلوب.",
    "appearanceTitle": "المظهر والسلامة",
    "appearance1": "اختار حذاء ثابت، مريح وآمن؛ الشبشب المفتوح أو الكعب العالي غير مناسبين عادةً.",
    "appearance2": "الشعر الطويل يتربط، ويتغطى لو الدور محتاج كده.",
    "appearance3": "الحلق وثقوب الجسم مسموحة عمومًا لو مش مبالغ فيها ومفيش منها خطر سلامة؛ أي وشم مسيء لازم يتغطى.",
    "appearance4": "لو بتتعامل مع أكل: الساعة تتشال، والخاتم يكون سادة فقط.",
    "foodAppearanceTitle": "الأظافر والأكل",
    "foodAppearanceValue": "في تجهيز أو إنتاج الطعام: ممنوع الأظافر الصناعية أو الجِل أو طلاء الأظافر. في أدوار بيع الأكل المغلف مسبقًا فيه مرونة، بشرط تكون الأظافر قصيرة ونظيفة وثابتة ومن غير زينة أو أجزاء ممكن تقع.",
    "uniformPolicyDate": "سياسة الزي والمظهر — تاريخ المراجعة 05/06/2026",
    "benefitsTitle": "مزايا الموظف",
    "mealBenefitTitle": "الأكل أثناء الشغل",
    "mealEntitlement": "الاستحقاق",
    "mealEntitlementValue": "وجبة واحدة لكل فترة راحة في الشفت",
    "freeBreakfast": "فطار مجاني",
    "freeBreakfastValue": "توست + إما عصيدة شوفان أو حبوب إفطار",
    "freeMeal": "غدا / عشا مجاني",
    "freeMealValue": "شوربة + إما خبز صغير أو ساندوتش مغلف + ثمرة فاكهة",
    "freeDrinks": "مشروبات مجانية",
    "freeDrinksValue": "شاي وقهوة أمريكانو + مياه ومشروبات مركزة من مناطق الموظفين",
    "otherDrinks": "مشروبات تانية",
    "otherDrinksValue": "خصم 50% على باقي المشروبات الساخنة والباردة حسب السياسة",
    "mealRulesTitle": "قواعد مهمة للوجبة",
    "mealRule1": "لازم كل حاجة — حتى المجاني — تتسجل على الكاشير قبل الأكل أو الخروج.",
    "mealRule2": "استخدم بطاقة Westmorland Family الخاصة بيك؛ ممنوع تخدم نفسك من ورا الكاونتر.",
    "mealRule3": "الوجبة للاستهلاك أثناء الشفت، مش للتخزين أو الأخذ للبيت.",
    "mealRule4": "الأكل ممنوع في مناطق تجهيز الطعام، المخازن أو أرضية البيع؛ والمشروبات تكون بعيد عن نظر العملاء.",
    "tebayDiscounts": "خصومات Tebay",
    "ownFood": "منتجات المطابخ والمطابخ السريعة اللي الشركة بتعملها",
    "ownFoodValue": "خصم 75%",
    "otherKitchenItems": "باقي منتجات المطابخ والمطابخ السريعة",
    "otherKitchenItemsValue": "خصم 50%",
    "specialityDrinks": "الشاي والقهوة المتخصصة / الكيك",
    "specialityDrinksValue": "خصم 50%",
    "shopDiscount": "المتجر",
    "shopDiscountValue": "خصم 25% عادةً؛ بعض المنتجات اللي بتتباع كمان في المطابخ ممكن تكون 50% أو 75%",
    "saleClothing": "ملابس عليها تخفيض",
    "saleClothingValue": "خصم 50% من السعر الأصلي",
    "noDiscountTitle": "مفيش خصم على",
    "noDiscountValue": "الوقود، اليانصيب وكروت الخدش، التبغ، الطوابع، معظم السلع المخفضة، عروض شراء عدة قطع، أسطوانات الغاز، PayPoint، وشحن رصيد الموبايل.",
    "hotelCinemaTitle": "الفندق وRheged",
    "hotelRooms": "فندق Westmorland",
    "hotelRoomsValue": "£60 إقامة مع إفطار لغرفة مزدوجة/توأم أو £50 لغرفة فردية — بحد أقصى 4 ليالي في السنة",
    "hotelFood": "أكل وشرب الفندق",
    "hotelFoodValue": "خصم 25% للمجموعة حتى 6 أشخاص",
    "cinema": "سينما Rheged",
    "cinemaValue": "دخول مجاني للأفلام نهارًا ومساءً حسب التوفر؛ الحجز شخصيًا من شباك التذاكر",
    "rhegedExtra": "مزايا Rheged",
    "rhegedExtraValue": "دخول المعرض مجانًا + منطقة اللعب الداخلية للأطفال مجانًا حسب التوفر",
    "otherBenefitsTitle": "مزايا تانية",
    "minibus": "الميني باص",
    "minibusValue": "نقل من وإلى الشغل",
    "birthdayLeave": "إجازة عيد الميلاد",
    "birthdayLeaveValue": "يوم إجازة مدفوع",
    "minibusProcedureTitle": "استخدام الميني باص",
    "minibusRule1": "سجّل نفسك كمستخدم للميني باص على My Westmorland People وحدد الخط.",
    "minibusRule2": "لازم تكون في نقطة الركوب المحددة قبل الميعاد؛ الباص مش بيستنى غير دقائق قليلة.",
    "minibusRule3": "لو مش هتحضر الشغل، بلّغ مديرك/الموقع بدري عشان اسمك يتشال من القائمة والسواق يعرف.",
    "minibusRule4": "اربط حزام الأمان طول الرحلة. ممنوع الأكل والشرب والتدخين أو استخدام السجائر الإلكترونية.",
    "minibusRule5": "الميني باص للشغل فقط: من وإلى مكان العمل في الشفتات المجدولة.",
    "minibusRule6": "تغيير نقطة الركوب أو النزول يحتاج استمارة جديدة للمدير؛ تغيير الخط يتم من My Westmorland People.",
    "kendalRouteMap": "افتح خريطة خط كندال",
    "kendalBusContact": "رقم ميني باص كندال",
    "personalNote": "ملاءمة الشفت",
    "nightMinibusNote": "الميني باص مش متاح لشفتات الجمعة والسبت بالليل.",
    "benefitsPolicyNote": "المزايا والسياسات قابلة للتعديل.",
    "duePrefix": "آخر موعد",
    "daysLeftOne": "فاضل يوم",
    "daysLeftMany": "فاضل {n} أيام",
    "dueToday": "آخر يوم النهارده",
    "overdueOne": "متأخر يوم",
    "overdueMany": "متأخر {n} أيام",
    "openTraining": "افتح تطبيق THRIVE",
    "resetChecklist": "ابدأ من جديد",
    "vaultNote": "أرقام وملاحظات خاصة.",
    "addPrivateEntry": "أضف بيانات خاصة",
    "home": "الرئيسية",
    "fireNav": "حريق",
    "detailsNav": "بياناتي",
    "trainingNav": "تدريب",
    "privateEntry": "بيانات خاصة",
    "label": "الاسم",
    "value": "القيمة",
    "noteOptional": "ملاحظة (اختياري)",
    "cancel": "إلغاء",
    "save": "حفظ",
    "noPrivateEntries": "مفيش بيانات خاصة لسه.",
    "reveal": "إظهار",
    "hide": "إخفاء",
    "copy": "نسخ",
    "copied": "اتنسخ",
    "delete": "حذف",
    "deleteConfirm": "تحذف البيانات دي؟",
    "wrongPass": "راجع بيانات الدخول.",
    "online": "متصل · النسخة الأوفلاين بتبقى متاحة بعد أول تحميل",
    "offline": "أوفلاين · المرجع محفوظ على الجهاز",
    "ready": "جاهز",
    "nowTitle": "المهم لشفتك",
    "myShift": "شفتّي",
    "nextLearning": "التدريب الجاي",
    "quickAccess": "وصول سريع",
    "allReference": "كل المراجع",
    "myTasks": "مهامي",
    "myProfile": "بياناتي",
    "fireQuick": "الحريق والإخلاء",
    "evacuationExit": "اخرج من أقرب مخرج حريق.",
    "evacuationAssembly": "كمّل لنقطة التجمع.",
    "add": "إضافة",
    "addTask": "مهمة واحدة…",
    "newShift": "ابدأ شفت جديد",
    "findReference": "بتدور على إيه؟",
    "otherAccount": "حساب تاني",
    "ownerAccount": "حسابي الحالي",
    "createAccount": "إنشاء حساب",
    "recoverAccount": "استرجاع الحساب",
    "accountName": "اسم المستخدم",
    "accountNameHint": "من ٣ إلى ٤٠ حرف إنجليزي أو رقم؛ مسموح بالنقطة والشرطة.",
    "newPasswordHint": "استخدم ١٢ حرف أو أكتر.",
    "accountUnavailable": "اسم المستخدم ده مش متاح.",
    "recoveryCode": "كود الاسترجاع",
    "keepRecovery": "احتفظ بالكود في مكان آمن. هتحتاجه لو نسيت كلمة المرور.",
    "done": "تم",
    "displayName": "الاسم",
    "manager": "المدير",
    "hours": "ساعات الأسبوع",
    "paidBreak": "الراحة",
    "annualHoliday": "الإجازة السنوية بالأيام",
    "minibusNote": "ملاحظة المواصلات",
    "shiftStart": "بداية الشفت",
    "shiftEnd": "نهاية الشفت",
    "shiftDays": "أيام الشفت",
    "hoursUnit": "ساعة",
    "addCourse": "إضافة كورس",
    "courseTitle": "اسم الكورس",
    "arabicTitleOptional": "الاسم بالعربي (اختياري)",
    "dueDate": "آخر موعد",
    "progressLabel": "التقدم",
    "notStarted": "لسه مبدأتش",
    "inProgress": "شغّال عليه",
    "optionalLearning": "اختياري",
    "learningClear": "خلصت المطلوب",
    "myProgress": "اختار كورس وكمّل",
    "addFirstTask": "أضف مهمة وابدأ قائمتك.",
    "deleteTaskConfirm": "تشيل المهمة دي؟",
    "deleteCourseConfirm": "تشيل الكورس ده من قائمتك؟",
    "grossEstimate": "أجر الأسبوع قبل الخصم (تقديري)",
    "firstDayTime": "وقت الحضور",
    "firstDayLocation": "مكان الحضور",
    "firstDayPostcode": "الرمز البريدي",
    "courseCount": "{n} كورسات",
    "myLearning": "قائمتي",
    "newIncident": "موقف جديد"
  },
  "en": {
    "back": "Back",
    "returnCompanion": "Return to Staff Companion",
    "logout": "Sign out",
    "apiError": "Unable to open your information. Please try again.",
    "tooMany": "Too many attempts. Please try again later.",
    "conflict": "Updated on another device. Reopen this section and try again.",
    "edit": "Edit",
    "editAccountDetails": "Edit account details",
    "workPin": "Work PIN",
    "thriveUsername": "THRIVE username",
    "importOldVault": "Import old vault",
    "importOldIntro": "Enter the old vault password for this device to import its entries. The old copy will be kept.",
    "oldPassword": "Old password",
    "importEntries": "Import",
    "importDone": "Entries imported and saved.",
    "emptyOldVault": "The old vault has no entries.",
    "importFailed": "Unable to open the old vault. Check its password.",
    "logoutFailed": "Information is locked here. Sign out could not finish; please try again.",
    "saveFailed": "Unable to save. Your entries are still open; please try again.",
    "invalidEntry": "Check the size of the information entered.",
    "appTitle": "WF Staff Companion",
    "enterPass": "Enter your password to open your personal information.",
    "passphrase": "Password",
    "unlock": "Unlock",
    "lock": "Lock",
    "fastReference": "Staff companion",
    "findSeconds": "Your shift, at a glance.",
    "confirmedOnly": "Act. Check. Find.",
    "emergency": "Emergency",
    "fire": "Fire",
    "reference": "Reference",
    "workDetails": "Work details",
    "training": "Training",
    "accountHelp": "Account help",
    "benefits": "Benefits",
    "uniformDress": "Uniform & dress",
    "privateVault": "Private vault",
    "backHome": "← Home",
    "fireHeadline": "FIRE ALARM → NEAREST FIRE EXIT → ASSEMBLY POINT",
    "fireIntro": "Use the nearest fire exit. Continue to the Assembly Point.",
    "forecourtSafe": "Forecourt — if safe to do so",
    "fireStep1": "Check Forecourt shop floor.",
    "fireStep2": "Check storeroom.",
    "fireStep3": "Check toilets.",
    "fireStep4": "Delegated team member takes the rota to the Assembly Point.",
    "onlyIfSafe": "Only if safe to do so.",
    "wardenTitle": "Fire Warden — only if you are assigned this role",
    "warden1": "Investigate the fire scene only if safe.",
    "warden2": "Activate the nearest break-glass point if not already done.",
    "warden3": "Tackle only an early-stage fire, only if safe and within company training.",
    "warden4": "Assist evacuation and liaise with managers/supervisors at the Assembly Point.",
    "warden5": "Prevent re-entry until the Fire Service says it is safe.",
    "warden6": "Brief the Fire Service on fire location/nature, anyone unaccounted for and hazards.",
    "myJob": "My job",
    "role": "Role",
    "roleValue": "Team Member – Filling Station (Nights)",
    "site": "Site",
    "lineManager": "Line manager",
    "managerEmail": "Manager email",
    "colleagueNumber": "Colleague number",
    "startDate": "Start date",
    "shiftPay": "Shift & pay",
    "regularShifts": "Regular shifts",
    "regularShiftsValue": "Friday & Saturday",
    "shiftTime": "Shift time",
    "contractedHours": "Contracted hours",
    "hourlyRate": "Hourly rate",
    "payFrequency": "Pay frequency",
    "weekly": "Weekly",
    "breakLabel": "Break",
    "breakValue": "Paid",
    "payrollTiming": "Year & payroll timing",
    "companyYear": "Year",
    "companyYearValue": "1 April – 31 March",
    "payWeekEnds": "Pay week closes",
    "payWeekEndsValue": "Sunday",
    "payDay": "Pay day",
    "payDayValue": "Following Friday — paid weekly",
    "kioskSettings": "Kiosk settings",
    "kioskId": "Kiosk ID",
    "kioskPin": "PIN",
    "temporaryId": "Temporary ID",
    "companyId": "Company ID",
    "username": "Username",
    "workspace": "Workspace",
    "openPeopleXD": "Open PeopleXD app",
    "openThrive": "Open THRIVE app",
    "firstDay": "First day / induction",
    "date": "Date",
    "time": "Time",
    "location": "Location",
    "inductionLocation": "Westmorland Hotel, Northbound",
    "postcode": "Postcode",
    "privateCodes": "Private codes",
    "privateCodesNote": "Your codes and account details.",
    "openVault": "Open Private Vault",
    "onlineTraining": "Online training",
    "requiredTraining": "Required training",
    "essentialLearning": "Essential Learning — current priority",
    "otherAssignedTraining": "Other assigned training",
    "completedLearning": "Completed learning",
    "completed": "Completed",
    "course1": "Welcome Antlers – Colleague Induction",
    "course2": "Food Safety Training",
    "course3": "Health & Safety Training",
    "course4": "Allergy Awareness Recap",
    "completed1": "Colleague Meal Procedure",
    "completed2": "NEW Seasonal Cakes from Westmorland Kitchen – Tebay…",
    "completed3": "How to… Learn Page",
    "completed4": "How to… Add Content",
    "completed5": "How to… Homepage & Explore",
    "completed6": "My Westmorland Learn",
    "completed7": "Cookery School Booklet",
    "completed8": "Careers Book",
    "completed9": "Ops Development Road Map",
    "completed10": "Our Family Values",
    "completed11": "Our Antlers Story",
    "completed12": "Our sites",
    "completed13": "Welcome Antlers – Colleague Overview",
    "completed14": "Launch Pack 'Food To Go' & 'Salads' Oct 26",
    "course5": "Customer Experience – The Westmorland Way",
    "course6": "CBE Procedures – Filling Station Colleagues",
    "course7": "Prevention of Sexual Harassment",
    "peopleAccessTitle": "PeopleXD access",
    "usernameRule": "Username",
    "usernameRuleValue": "Your colleague number — 6 digits and starts with 0",
    "usernameUnknown": "If you do not know it",
    "usernameUnknownValue": "Ask your line manager or email help@mywestmorland.com with your full name",
    "forgotPassword": "Forgot password",
    "resetStep1": "Open mywestmorland.com.",
    "resetStep2": "My Westmorland People → Forgot Password.",
    "resetStep3": "Colleague number + date of birth → Reset Password.",
    "resetStep4": "Open the reset email. Confirm your details and set a new password.",
    "openResetSite": "Open PeopleXD reset page",
    "bothForgotten": "Forgot password and security questions?",
    "bothForgottenValue": "Email help@mywestmorland.com with your full name. The People Team will manually reset access.",
    "emailPeopleTeam": "Email People Team",
    "passwordRules": "Password rules",
    "passwordRulesValue": "12+ characters: uppercase, lowercase, number and symbol.",
    "appFallback": "If the app is not working",
    "appFallbackValue": "Use mywestmorland.com for PeopleXD, including holiday booking. If needed, try an updated device, laptop or tablet.",
    "openBrowserPortal": "Open PeopleXD in browser",
    "uniformTitle": "Uniform & dress",
    "uniformProvided": "Company provides",
    "uniformProvidedValue": "Most required uniform free of charge — typically T-shirts/shirts, aprons, fleeces or jumpers",
    "ownItems": "Usually your own",
    "ownItemsValue": "Trousers and footwear, unless safety footwear is issued as PPE",
    "replacement": "Replacement",
    "replacementValue": "Normally free for reasonable wear and tear; charges may apply beyond that",
    "outsideWork": "Outdoor work",
    "outsideWorkValue": "Warm and waterproof clothing is provided; hats and sunscreen may also be available in summer",
    "ppeTitle": "PPE",
    "ppeValue": "If safety footwear, high-vis or other PPE is issued for your role, it must be worn when required.",
    "appearanceTitle": "Appearance & safety",
    "appearance1": "Wear sturdy, comfortable and safe footwear; flip-flops and high heels are normally unsuitable.",
    "appearance2": "Tie back long hair and cover it where required.",
    "appearance3": "Piercings are generally acceptable if not excessive or a safety risk; offensive tattoos must be covered.",
    "appearance4": "When working with food, remove watches and wear only a plain ring.",
    "foodAppearanceTitle": "Nails & food work",
    "foodAppearanceValue": "Food preparation/production: no false nails, gel nails or nail varnish. Pre-packed food retail has some flexibility, but nails must be short, clean, secure and free from jewels or loose additions.",
    "uniformPolicyDate": "Uniform & Dress Policy — review date 05/06/2026",
    "benefitsTitle": "Staff benefits",
    "mealBenefitTitle": "Meals at work",
    "mealEntitlement": "Entitlement",
    "mealEntitlementValue": "One meal entitlement per break in your shift",
    "freeBreakfast": "Free breakfast",
    "freeBreakfastValue": "Toast + either porridge or cereal",
    "freeMeal": "Free lunch / evening meal",
    "freeMealValue": "Soup + either a bread roll or boxed/wrapped sandwich + one piece of fruit",
    "freeDrinks": "Free drinks",
    "freeDrinksValue": "Tea and Americano + water and cordials from colleague areas",
    "otherDrinks": "Other drinks",
    "otherDrinksValue": "50% off other hot and cold drinks where covered by policy",
    "mealRulesTitle": "Meal rules",
    "mealRule1": "Everything — including free items — must be processed through the till before eating or leaving the unit.",
    "mealRule2": "Use your own Westmorland Family Card; do not serve yourself from behind the counter.",
    "mealRule3": "Meal items are for consumption during the shift, not for later or to take home.",
    "mealRule4": "Do not eat in food-preparation areas, stock rooms or on the sales floor; keep drinks out of customers’ view.",
    "tebayDiscounts": "Tebay discounts",
    "ownFood": "Kitchens / Quick Kitchens items made by the company",
    "ownFoodValue": "75% off",
    "otherKitchenItems": "Other Kitchens / Quick Kitchens items",
    "otherKitchenItemsValue": "50% off",
    "specialityDrinks": "Speciality teas & coffees / cakes",
    "specialityDrinksValue": "50% off",
    "shopDiscount": "Shops",
    "shopDiscountValue": "Usually 25% off; items also sold in Kitchens may qualify for 50% or 75%",
    "saleClothing": "Clothing reduced in a sale",
    "saleClothingValue": "50% off the original selling price",
    "noDiscountTitle": "No discount on",
    "noDiscountValue": "Fuel, lottery/scratch cards, tobacco, stamps, most reduced items, multi-buy promotions, gas cylinders, PayPoint and mobile top-ups.",
    "hotelCinemaTitle": "Hotel & Rheged",
    "hotelRooms": "Westmorland Hotel",
    "hotelRoomsValue": "£60 B&B double/twin or £50 B&B single — maximum 4 nights per year",
    "hotelFood": "Hotel food & drink",
    "hotelFoodValue": "25% off the total bill for groups up to 6",
    "cinema": "Rheged cinema",
    "cinemaValue": "Free entry to daytime and evening films, subject to availability; book in person at the box office",
    "rhegedExtra": "Rheged extras",
    "rhegedExtraValue": "Free Gallery entry + free indoor play for children, subject to availability",
    "otherBenefitsTitle": "Other benefits",
    "minibus": "Minibus",
    "minibusValue": "Transport to and from work",
    "birthdayLeave": "Birthday leave",
    "birthdayLeaveValue": "One paid day off",
    "minibusProcedureTitle": "Using the minibus",
    "minibusRule1": "Register as a minibus user in My Westmorland People and select the route you need.",
    "minibusRule2": "Be at the designated pick-up point before the stated time; the bus only waits a few minutes.",
    "minibusRule3": "If you will not attend work, tell your manager/site in advance so the driver can be informed and your name removed.",
    "minibusRule4": "Wear a seat belt at all times. No food/drink, smoking or vaping.",
    "minibusRule5": "The minibus is only for travel to and from work on scheduled shifts.",
    "minibusRule6": "Change of pick-up/drop-off needs a new form to your manager; route changes are requested in My Westmorland People.",
    "kendalRouteMap": "Open Kendal route map",
    "kendalBusContact": "Kendal bus contact",
    "personalNote": "Shift applicability",
    "nightMinibusNote": "Minibus unavailable for Friday/Saturday night shifts.",
    "benefitsPolicyNote": "Benefits and policies may be amended.",
    "duePrefix": "Due",
    "daysLeftOne": "1 day left",
    "daysLeftMany": "{n} days left",
    "dueToday": "Due today",
    "overdueOne": "1 day overdue",
    "overdueMany": "{n} days overdue",
    "openTraining": "Open THRIVE app",
    "resetChecklist": "Reset checks",
    "vaultNote": "Private codes and notes.",
    "addPrivateEntry": "Add private entry",
    "home": "Home",
    "fireNav": "Fire",
    "detailsNav": "Details",
    "trainingNav": "Training",
    "privateEntry": "Private entry",
    "label": "Label",
    "value": "Value",
    "noteOptional": "Note (optional)",
    "cancel": "Cancel",
    "save": "Save",
    "noPrivateEntries": "No private entries yet.",
    "reveal": "Reveal",
    "hide": "Hide",
    "copy": "Copy",
    "copied": "Copied",
    "delete": "Delete",
    "deleteConfirm": "Delete this private entry?",
    "wrongPass": "Check your sign-in details.",
    "online": "Online · offline copy available after first load",
    "offline": "Offline · cached reference",
    "ready": "Ready",
    "nowTitle": "For your shift",
    "myShift": "My shift",
    "nextLearning": "Next to learn",
    "quickAccess": "Quick access",
    "allReference": "All reference",
    "myTasks": "My tasks",
    "myProfile": "My profile",
    "fireQuick": "Fire & evacuation",
    "evacuationExit": "Use the nearest fire exit.",
    "evacuationAssembly": "Continue to the Assembly Point.",
    "add": "Add",
    "addTask": "One task…",
    "newShift": "Reset for a new shift",
    "findReference": "Find a reference…",
    "otherAccount": "Another account",
    "ownerAccount": "My existing account",
    "createAccount": "Create account",
    "recoverAccount": "Recover account",
    "accountName": "Username",
    "accountNameHint": "Use 3–40 letters, numbers, dots, underscores or hyphens.",
    "newPasswordHint": "Use at least 12 characters.",
    "accountUnavailable": "That username is unavailable.",
    "recoveryCode": "Recovery code",
    "keepRecovery": "Keep this code somewhere safe. You need it if you forget your password.",
    "done": "Done",
    "displayName": "Name",
    "manager": "Manager",
    "hours": "Weekly hours",
    "paidBreak": "Break",
    "annualHoliday": "Annual holiday (days)",
    "minibusNote": "Travel note",
    "shiftStart": "Shift starts",
    "shiftEnd": "Shift ends",
    "shiftDays": "Shift days",
    "hoursUnit": "hours",
    "addCourse": "Add course",
    "courseTitle": "Course title",
    "arabicTitleOptional": "Arabic title (optional)",
    "dueDate": "Due date",
    "progressLabel": "Progress",
    "notStarted": "Not started",
    "inProgress": "In progress",
    "optionalLearning": "Optional",
    "learningClear": "Required learning complete",
    "myProgress": "Pick a course and continue",
    "addFirstTask": "Add a task to start your checklist.",
    "deleteTaskConfirm": "Remove this task?",
    "deleteCourseConfirm": "Remove this course from your list?",
    "grossEstimate": "Weekly gross estimate",
    "firstDayTime": "Arrival time",
    "firstDayLocation": "Arrival location",
    "firstDayPostcode": "Postcode",
    "courseCount": "{n} courses",
    "myLearning": "My learning",
    "newIncident": "New incident"
  }
};
